package com.worldsofminecraft.resource.vanilla;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.function.Supplier;

import com.worldsofminecraft.mod.util.Volatile;

import net.minecraft.item.Item;
import net.minecraft.item.Items;

/**
 * A {@link VanillaItem} is a reference to an item that comes as part of Vanilla
 * Minecraft.
 * 
 * @author Joseph Collard <jcollard@worldsofminecraft.com>
 *
 */
public enum VanillaItem {

	ACACIA_BOAT("item/acacia_boat", () -> Items.ACACIA_BOAT),
	ACACIA_BUTTON("item/acacia_button", () -> Items.ACACIA_BUTTON),
	ACACIA_DOOR("item/acacia_door", () -> Items.ACACIA_DOOR),
	ACACIA_FENCE("item/acacia_fence", () -> Items.ACACIA_FENCE),
	ACACIA_FENCE_GATE("item/acacia_fence_gate", () -> Items.ACACIA_FENCE_GATE),
	ACACIA_LEAVES("item/acacia_leaves", () -> Items.ACACIA_LEAVES),
	ACACIA_LOG("item/acacia_log", () -> Items.ACACIA_LOG),
	ACACIA_PLANKS("item/acacia_planks", () -> Items.ACACIA_PLANKS),
	ACACIA_PRESSURE_PLATE("item/acacia_pressure_plate", () -> Items.ACACIA_PRESSURE_PLATE),
	ACACIA_SAPLING("item/acacia_sapling", () -> Items.ACACIA_SAPLING),
	ACACIA_SIGN("item/acacia_sign", () -> Items.ACACIA_SIGN), ACACIA_SLAB("item/acacia_slab", () -> Items.ACACIA_SLAB),
	ACACIA_STAIRS("item/acacia_stairs", () -> Items.ACACIA_STAIRS),
	ACACIA_TRAPDOOR("item/acacia_trapdoor", () -> Items.ACACIA_TRAPDOOR),
	ACACIA_WOOD("item/acacia_wood", () -> Items.ACACIA_WOOD),
	ACTIVATOR_RAIL("item/activator_rail", () -> Items.ACTIVATOR_RAIL), AIR("item/air", () -> Items.AIR),
	ALLIUM("item/allium", () -> Items.ALLIUM), ANCIENT_DEBRIS("item/ancient_debris", () -> Items.ANCIENT_DEBRIS),
	ANDESITE("item/andesite", () -> Items.ANDESITE), ANDESITE_SLAB("item/andesite_slab", () -> Items.ANDESITE_SLAB),
	ANDESITE_STAIRS("item/andesite_stairs", () -> Items.ANDESITE_STAIRS),
	ANDESITE_WALL("item/andesite_wall", () -> Items.ANDESITE_WALL), ANVIL("item/anvil", () -> Items.ANVIL),
	APPLE("item/apple", () -> Items.APPLE), ARMOR_STAND("item/armor_stand", () -> Items.ARMOR_STAND),
	ARROW("item/arrow", () -> Items.ARROW), AZURE_BLUET("item/azure_bluet", () -> Items.AZURE_BLUET),
	BAKED_POTATO("item/baked_potato", () -> Items.BAKED_POTATO), BAMBOO("item/bamboo", () -> Items.BAMBOO),
	BARREL("item/barrel", () -> Items.BARREL), BARRIER("item/barrier", () -> Items.BARRIER),
	BASALT("item/basalt", () -> Items.BASALT), BAT_SPAWN_EGG("item/bat_spawn_egg", () -> Items.BAT_SPAWN_EGG),
	BEACON("item/beacon", () -> Items.BEACON), BEDROCK("item/bedrock", () -> Items.BEDROCK),
	BEE_NEST("item/bee_nest", () -> Items.BEE_NEST), BEE_SPAWN_EGG("item/bee_spawn_egg", () -> Items.BEE_SPAWN_EGG),
	BEEF("item/beef", () -> Items.BEEF), BEEHIVE("item/beehive", () -> Items.BEEHIVE),
	BEETROOT("item/beetroot", () -> Items.BEETROOT), BEETROOT_SEEDS("item/beetroot_seeds", () -> Items.BEETROOT_SEEDS),
	BEETROOT_SOUP("item/beetroot_soup", () -> Items.BEETROOT_SOUP), BELL("item/bell", () -> Items.BELL),
	BIRCH_BOAT("item/birch_boat", () -> Items.BIRCH_BOAT), BIRCH_BUTTON("item/birch_button", () -> Items.BIRCH_BUTTON),
	BIRCH_DOOR("item/birch_door", () -> Items.BIRCH_DOOR), BIRCH_FENCE("item/birch_fence", () -> Items.BIRCH_FENCE),
	BIRCH_FENCE_GATE("item/birch_fence_gate", () -> Items.BIRCH_FENCE_GATE),
	BIRCH_LEAVES("item/birch_leaves", () -> Items.BIRCH_LEAVES), BIRCH_LOG("item/birch_log", () -> Items.BIRCH_LOG),
	BIRCH_PLANKS("item/birch_planks", () -> Items.BIRCH_PLANKS),
	BIRCH_PRESSURE_PLATE("item/birch_pressure_plate", () -> Items.BIRCH_PRESSURE_PLATE),
	BIRCH_SAPLING("item/birch_sapling", () -> Items.BIRCH_SAPLING),
	BIRCH_SIGN("item/birch_sign", () -> Items.BIRCH_SIGN), BIRCH_SLAB("item/birch_slab", () -> Items.BIRCH_SLAB),
	BIRCH_STAIRS("item/birch_stairs", () -> Items.BIRCH_STAIRS),
	BIRCH_TRAPDOOR("item/birch_trapdoor", () -> Items.BIRCH_TRAPDOOR),
	BIRCH_WOOD("item/birch_wood", () -> Items.BIRCH_WOOD), BLACK_BANNER("item/black_banner", () -> Items.BLACK_BANNER),
	BLACK_BED("item/black_bed", () -> Items.BLACK_BED), BLACK_CARPET("item/black_carpet", () -> Items.BLACK_CARPET),
	BLACK_CONCRETE("item/black_concrete", () -> Items.BLACK_CONCRETE),
	BLACK_CONCRETE_POWDER("item/black_concrete_powder", () -> Items.BLACK_CONCRETE_POWDER),
	BLACK_DYE("item/black_dye", () -> Items.BLACK_DYE),
	BLACK_GLAZED_TERRACOTTA("item/black_glazed_terracotta", () -> Items.BLACK_GLAZED_TERRACOTTA),
	BLACK_SHULKER_BOX("item/black_shulker_box", () -> Items.BLACK_SHULKER_BOX),
	BLACK_STAINED_GLASS("item/black_stained_glass", () -> Items.BLACK_STAINED_GLASS),
	BLACK_STAINED_GLASS_PANE("item/black_stained_glass_pane", () -> Items.BLACK_STAINED_GLASS_PANE),
	BLACK_TERRACOTTA("item/black_terracotta", () -> Items.BLACK_TERRACOTTA),
	BLACK_WOOL("item/black_wool", () -> Items.BLACK_WOOL), BLACKSTONE("item/blackstone", () -> Items.BLACKSTONE),
	BLACKSTONE_SLAB("item/blackstone_slab", () -> Items.BLACKSTONE_SLAB),
	BLACKSTONE_STAIRS("item/blackstone_stairs", () -> Items.BLACKSTONE_STAIRS),
	BLACKSTONE_WALL("item/blackstone_wall", () -> Items.BLACKSTONE_WALL),
	BLAST_FURNACE("item/blast_furnace", () -> Items.BLAST_FURNACE),
	BLAZE_POWDER("item/blaze_powder", () -> Items.BLAZE_POWDER), BLAZE_ROD("item/blaze_rod", () -> Items.BLAZE_ROD),
	BLAZE_SPAWN_EGG("item/blaze_spawn_egg", () -> Items.BLAZE_SPAWN_EGG),
	BLUE_BANNER("item/blue_banner", () -> Items.BLUE_BANNER), BLUE_BED("item/blue_bed", () -> Items.BLUE_BED),
	BLUE_CARPET("item/blue_carpet", () -> Items.BLUE_CARPET),
	BLUE_CONCRETE("item/blue_concrete", () -> Items.BLUE_CONCRETE),
	BLUE_CONCRETE_POWDER("item/blue_concrete_powder", () -> Items.BLUE_CONCRETE_POWDER),
	BLUE_DYE("item/blue_dye", () -> Items.BLUE_DYE),
	BLUE_GLAZED_TERRACOTTA("item/blue_glazed_terracotta", () -> Items.BLUE_GLAZED_TERRACOTTA),
	BLUE_ICE("item/blue_ice", () -> Items.BLUE_ICE), BLUE_ORCHID("item/blue_orchid", () -> Items.BLUE_ORCHID),
	BLUE_SHULKER_BOX("item/blue_shulker_box", () -> Items.BLUE_SHULKER_BOX),
	BLUE_STAINED_GLASS("item/blue_stained_glass", () -> Items.BLUE_STAINED_GLASS),
	BLUE_STAINED_GLASS_PANE("item/blue_stained_glass_pane", () -> Items.BLUE_STAINED_GLASS_PANE),
	BLUE_TERRACOTTA("item/blue_terracotta", () -> Items.BLUE_TERRACOTTA),
	BLUE_WOOL("item/blue_wool", () -> Items.BLUE_WOOL), BONE("item/bone", () -> Items.BONE),
	BONE_BLOCK("item/bone_block", () -> Items.BONE_BLOCK), BONE_MEAL("item/bone_meal", () -> Items.BONE_MEAL),
	BOOK("item/book", () -> Items.BOOK), BOOKSHELF("item/bookshelf", () -> Items.BOOKSHELF),
	BOW("item/bow", () -> Items.BOW), BOWL("item/bowl", () -> Items.BOWL),
	BRAIN_CORAL("item/brain_coral", () -> Items.BRAIN_CORAL),
	BRAIN_CORAL_BLOCK("item/brain_coral_block", () -> Items.BRAIN_CORAL_BLOCK),
	BRAIN_CORAL_FAN("item/brain_coral_fan", () -> Items.BRAIN_CORAL_FAN), BREAD("item/bread", () -> Items.BREAD),
	BREWING_STAND("item/brewing_stand", () -> Items.BREWING_STAND), BRICK("item/brick", () -> Items.BRICK),
	BRICK_SLAB("item/brick_slab", () -> Items.BRICK_SLAB), BRICK_STAIRS("item/brick_stairs", () -> Items.BRICK_STAIRS),
	BRICK_WALL("item/brick_wall", () -> Items.BRICK_WALL), BRICKS("item/bricks", () -> Items.BRICKS),
	BROWN_BANNER("item/brown_banner", () -> Items.BROWN_BANNER), BROWN_BED("item/brown_bed", () -> Items.BROWN_BED),
	BROWN_CARPET("item/brown_carpet", () -> Items.BROWN_CARPET),
	BROWN_CONCRETE("item/brown_concrete", () -> Items.BROWN_CONCRETE),
	BROWN_CONCRETE_POWDER("item/brown_concrete_powder", () -> Items.BROWN_CONCRETE_POWDER),
	BROWN_DYE("item/brown_dye", () -> Items.BROWN_DYE),
	BROWN_GLAZED_TERRACOTTA("item/brown_glazed_terracotta", () -> Items.BROWN_GLAZED_TERRACOTTA),
	BROWN_MUSHROOM("item/brown_mushroom", () -> Items.BROWN_MUSHROOM),
	BROWN_MUSHROOM_BLOCK("item/brown_mushroom_block", () -> Items.BROWN_MUSHROOM_BLOCK),
	BROWN_SHULKER_BOX("item/brown_shulker_box", () -> Items.BROWN_SHULKER_BOX),
	BROWN_STAINED_GLASS("item/brown_stained_glass", () -> Items.BROWN_STAINED_GLASS),
	BROWN_STAINED_GLASS_PANE("item/brown_stained_glass_pane", () -> Items.BROWN_STAINED_GLASS_PANE),
	BROWN_TERRACOTTA("item/brown_terracotta", () -> Items.BROWN_TERRACOTTA),
	BROWN_WOOL("item/brown_wool", () -> Items.BROWN_WOOL), BUBBLE_CORAL("item/bubble_coral", () -> Items.BUBBLE_CORAL),
	BUBBLE_CORAL_BLOCK("item/bubble_coral_block", () -> Items.BUBBLE_CORAL_BLOCK),
	BUBBLE_CORAL_FAN("item/bubble_coral_fan", () -> Items.BUBBLE_CORAL_FAN), BUCKET("item/bucket", () -> Items.BUCKET),
	CACTUS("item/cactus", () -> Items.CACTUS), CAKE("item/cake", () -> Items.CAKE),
	CAMPFIRE("item/campfire", () -> Items.CAMPFIRE), CARROT("item/carrot", () -> Items.CARROT),
	CARROT_ON_A_STICK("item/carrot_on_a_stick", () -> Items.CARROT_ON_A_STICK),
	CARTOGRAPHY_TABLE("item/cartography_table", () -> Items.CARTOGRAPHY_TABLE),
	CARVED_PUMPKIN("item/carved_pumpkin", () -> Items.CARVED_PUMPKIN),
	CAT_SPAWN_EGG("item/cat_spawn_egg", () -> Items.CAT_SPAWN_EGG), CAULDRON("item/cauldron", () -> Items.CAULDRON),
	CAVE_SPIDER_SPAWN_EGG("item/cave_spider_spawn_egg", () -> Items.CAVE_SPIDER_SPAWN_EGG),
	CHAIN("item/chain", () -> Items.CHAIN),
	CHAIN_COMMAND_BLOCK("item/chain_command_block", () -> Items.CHAIN_COMMAND_BLOCK),
	CHAINMAIL_BOOTS("item/chainmail_boots", () -> Items.CHAINMAIL_BOOTS),
	CHAINMAIL_CHESTPLATE("item/chainmail_chestplate", () -> Items.CHAINMAIL_CHESTPLATE),
	CHAINMAIL_HELMET("item/chainmail_helmet", () -> Items.CHAINMAIL_HELMET),
	CHAINMAIL_LEGGINGS("item/chainmail_leggings", () -> Items.CHAINMAIL_LEGGINGS),
	CHARCOAL("item/charcoal", () -> Items.CHARCOAL), CHEST("item/chest", () -> Items.CHEST),
	CHEST_MINECART("item/chest_minecart", () -> Items.CHEST_MINECART), CHICKEN("item/chicken", () -> Items.CHICKEN),
	CHICKEN_SPAWN_EGG("item/chicken_spawn_egg", () -> Items.CHICKEN_SPAWN_EGG),
	CHIPPED_ANVIL("item/chipped_anvil", () -> Items.CHIPPED_ANVIL),
	CHISELED_NETHER_BRICKS("item/chiseled_nether_bricks", () -> Items.CHISELED_NETHER_BRICKS),
	CHISELED_POLISHED_BLACKSTONE("item/chiseled_polished_blackstone", () -> Items.CHISELED_POLISHED_BLACKSTONE),
	CHISELED_QUARTZ_BLOCK("item/chiseled_quartz_block", () -> Items.CHISELED_QUARTZ_BLOCK),
	CHISELED_RED_SANDSTONE("item/chiseled_red_sandstone", () -> Items.CHISELED_RED_SANDSTONE),
	CHISELED_SANDSTONE("item/chiseled_sandstone", () -> Items.CHISELED_SANDSTONE),
	CHISELED_STONE_BRICKS("item/chiseled_stone_bricks", () -> Items.CHISELED_STONE_BRICKS),
	CHORUS_FLOWER("item/chorus_flower", () -> Items.CHORUS_FLOWER),
	CHORUS_FRUIT("item/chorus_fruit", () -> Items.CHORUS_FRUIT),
	CHORUS_PLANT("item/chorus_plant", () -> Items.CHORUS_PLANT), CLAY("item/clay", () -> Items.CLAY),
	CLAY_BALL("item/clay_ball", () -> Items.CLAY_BALL), CLOCK("item/clock", () -> Items.CLOCK),
	COAL("item/coal", () -> Items.COAL), COAL_BLOCK("item/coal_block", () -> Items.COAL_BLOCK),
	COAL_ORE("item/coal_ore", () -> Items.COAL_ORE), COARSE_DIRT("item/coarse_dirt", () -> Items.COARSE_DIRT),
	COBBLESTONE("item/cobblestone", () -> Items.COBBLESTONE),
	COBBLESTONE_SLAB("item/cobblestone_slab", () -> Items.COBBLESTONE_SLAB),
	COBBLESTONE_STAIRS("item/cobblestone_stairs", () -> Items.COBBLESTONE_STAIRS),
	COBBLESTONE_WALL("item/cobblestone_wall", () -> Items.COBBLESTONE_WALL), COBWEB("item/cobweb", () -> Items.COBWEB),
	COCOA_BEANS("item/cocoa_beans", () -> Items.COCOA_BEANS), COD("item/cod", () -> Items.COD),
	COD_BUCKET("item/cod_bucket", () -> Items.COD_BUCKET),
	COD_SPAWN_EGG("item/cod_spawn_egg", () -> Items.COD_SPAWN_EGG),
	COMMAND_BLOCK("item/command_block", () -> Items.COMMAND_BLOCK),
	COMMAND_BLOCK_MINECART("item/command_block_minecart", () -> Items.COMMAND_BLOCK_MINECART),
	COMPARATOR("item/comparator", () -> Items.COMPARATOR), COMPASS("item/compass", () -> Items.COMPASS),
	COMPOSTER("item/composter", () -> Items.COMPOSTER), CONDUIT("item/conduit", () -> Items.CONDUIT),
	COOKED_BEEF("item/cooked_beef", () -> Items.COOKED_BEEF),
	COOKED_CHICKEN("item/cooked_chicken", () -> Items.COOKED_CHICKEN),
	COOKED_COD("item/cooked_cod", () -> Items.COOKED_COD),
	COOKED_MUTTON("item/cooked_mutton", () -> Items.COOKED_MUTTON),
	COOKED_PORKCHOP("item/cooked_porkchop", () -> Items.COOKED_PORKCHOP),
	COOKED_RABBIT("item/cooked_rabbit", () -> Items.COOKED_RABBIT),
	COOKED_SALMON("item/cooked_salmon", () -> Items.COOKED_SALMON), COOKIE("item/cookie", () -> Items.COOKIE),
	CORNFLOWER("item/cornflower", () -> Items.CORNFLOWER),
	COW_SPAWN_EGG("item/cow_spawn_egg", () -> Items.COW_SPAWN_EGG),
	CRACKED_NETHER_BRICKS("item/cracked_nether_bricks", () -> Items.CRACKED_NETHER_BRICKS),
	CRACKED_POLISHED_BLACKSTONE_BRICKS("item/cracked_polished_blackstone_bricks",
			() -> Items.CRACKED_POLISHED_BLACKSTONE_BRICKS),
	CRACKED_STONE_BRICKS("item/cracked_stone_bricks", () -> Items.CRACKED_STONE_BRICKS),
	CRAFTING_TABLE("item/crafting_table", () -> Items.CRAFTING_TABLE),
	CREEPER_BANNER_PATTERN("item/creeper_banner_pattern", () -> Items.CREEPER_BANNER_PATTERN),
	CREEPER_HEAD("item/creeper_head", () -> Items.CREEPER_HEAD),
	CREEPER_SPAWN_EGG("item/creeper_spawn_egg", () -> Items.CREEPER_SPAWN_EGG),
	CRIMSON_BUTTON("item/crimson_button", () -> Items.CRIMSON_BUTTON),
	CRIMSON_DOOR("item/crimson_door", () -> Items.CRIMSON_DOOR),
	CRIMSON_FENCE("item/crimson_fence", () -> Items.CRIMSON_FENCE),
	CRIMSON_FENCE_GATE("item/crimson_fence_gate", () -> Items.CRIMSON_FENCE_GATE),
	CRIMSON_FUNGUS("item/crimson_fungus", () -> Items.CRIMSON_FUNGUS),
	CRIMSON_HYPHAE("item/crimson_hyphae", () -> Items.CRIMSON_HYPHAE),
	CRIMSON_NYLIUM("item/crimson_nylium", () -> Items.CRIMSON_NYLIUM),
	CRIMSON_PLANKS("item/crimson_planks", () -> Items.CRIMSON_PLANKS),
	CRIMSON_PRESSURE_PLATE("item/crimson_pressure_plate", () -> Items.CRIMSON_PRESSURE_PLATE),
	CRIMSON_ROOTS("item/crimson_roots", () -> Items.CRIMSON_ROOTS),
	CRIMSON_SIGN("item/crimson_sign", () -> Items.CRIMSON_SIGN),
	CRIMSON_SLAB("item/crimson_slab", () -> Items.CRIMSON_SLAB),
	CRIMSON_STAIRS("item/crimson_stairs", () -> Items.CRIMSON_STAIRS),
	CRIMSON_STEM("item/crimson_stem", () -> Items.CRIMSON_STEM),
	CRIMSON_TRAPDOOR("item/crimson_trapdoor", () -> Items.CRIMSON_TRAPDOOR),
	CROSSBOW("item/crossbow", () -> Items.CROSSBOW),
	CRYING_OBSIDIAN("item/crying_obsidian", () -> Items.CRYING_OBSIDIAN),
	CUT_RED_SANDSTONE("item/cut_red_sandstone", () -> Items.CUT_RED_SANDSTONE),
	CUT_RED_SANDSTONE_SLAB("item/cut_red_sandstone_slab", () -> Items.CUT_RED_SANDSTONE_SLAB),
	CUT_SANDSTONE("item/cut_sandstone", () -> Items.CUT_SANDSTONE),
	CYAN_BANNER("item/cyan_banner", () -> Items.CYAN_BANNER), CYAN_BED("item/cyan_bed", () -> Items.CYAN_BED),
	CYAN_CARPET("item/cyan_carpet", () -> Items.CYAN_CARPET),
	CYAN_CONCRETE("item/cyan_concrete", () -> Items.CYAN_CONCRETE),
	CYAN_CONCRETE_POWDER("item/cyan_concrete_powder", () -> Items.CYAN_CONCRETE_POWDER),
	CYAN_DYE("item/cyan_dye", () -> Items.CYAN_DYE),
	CYAN_GLAZED_TERRACOTTA("item/cyan_glazed_terracotta", () -> Items.CYAN_GLAZED_TERRACOTTA),
	CYAN_SHULKER_BOX("item/cyan_shulker_box", () -> Items.CYAN_SHULKER_BOX),
	CYAN_STAINED_GLASS("item/cyan_stained_glass", () -> Items.CYAN_STAINED_GLASS),
	CYAN_STAINED_GLASS_PANE("item/cyan_stained_glass_pane", () -> Items.CYAN_STAINED_GLASS_PANE),
	CYAN_TERRACOTTA("item/cyan_terracotta", () -> Items.CYAN_TERRACOTTA),
	CYAN_WOOL("item/cyan_wool", () -> Items.CYAN_WOOL), DAMAGED_ANVIL("item/damaged_anvil", () -> Items.DAMAGED_ANVIL),
	DANDELION("item/dandelion", () -> Items.DANDELION), DARK_OAK_BOAT("item/dark_oak_boat", () -> Items.DARK_OAK_BOAT),
	DARK_OAK_BUTTON("item/dark_oak_button", () -> Items.DARK_OAK_BUTTON),
	DARK_OAK_DOOR("item/dark_oak_door", () -> Items.DARK_OAK_DOOR),
	DARK_OAK_FENCE("item/dark_oak_fence", () -> Items.DARK_OAK_FENCE),
	DARK_OAK_FENCE_GATE("item/dark_oak_fence_gate", () -> Items.DARK_OAK_FENCE_GATE),
	DARK_OAK_LEAVES("item/dark_oak_leaves", () -> Items.DARK_OAK_LEAVES),
	DARK_OAK_LOG("item/dark_oak_log", () -> Items.DARK_OAK_LOG),
	DARK_OAK_PLANKS("item/dark_oak_planks", () -> Items.DARK_OAK_PLANKS),
	DARK_OAK_PRESSURE_PLATE("item/dark_oak_pressure_plate", () -> Items.DARK_OAK_PRESSURE_PLATE),
	DARK_OAK_SAPLING("item/dark_oak_sapling", () -> Items.DARK_OAK_SAPLING),
	DARK_OAK_SIGN("item/dark_oak_sign", () -> Items.DARK_OAK_SIGN),
	DARK_OAK_SLAB("item/dark_oak_slab", () -> Items.DARK_OAK_SLAB),
	DARK_OAK_STAIRS("item/dark_oak_stairs", () -> Items.DARK_OAK_STAIRS),
	DARK_OAK_TRAPDOOR("item/dark_oak_trapdoor", () -> Items.DARK_OAK_TRAPDOOR),
	DARK_OAK_WOOD("item/dark_oak_wood", () -> Items.DARK_OAK_WOOD),
	DARK_PRISMARINE("item/dark_prismarine", () -> Items.DARK_PRISMARINE),
	DARK_PRISMARINE_SLAB("item/dark_prismarine_slab", () -> Items.DARK_PRISMARINE_SLAB),
	DARK_PRISMARINE_STAIRS("item/dark_prismarine_stairs", () -> Items.DARK_PRISMARINE_STAIRS),
	DAYLIGHT_DETECTOR("item/daylight_detector", () -> Items.DAYLIGHT_DETECTOR),
	DEAD_BRAIN_CORAL("item/dead_brain_coral", () -> Items.DEAD_BRAIN_CORAL),
	DEAD_BRAIN_CORAL_BLOCK("item/dead_brain_coral_block", () -> Items.DEAD_BRAIN_CORAL_BLOCK),
	DEAD_BRAIN_CORAL_FAN("item/dead_brain_coral_fan", () -> Items.DEAD_BRAIN_CORAL_FAN),
	DEAD_BUBBLE_CORAL("item/dead_bubble_coral", () -> Items.DEAD_BUBBLE_CORAL),
	DEAD_BUBBLE_CORAL_BLOCK("item/dead_bubble_coral_block", () -> Items.DEAD_BUBBLE_CORAL_BLOCK),
	DEAD_BUBBLE_CORAL_FAN("item/dead_bubble_coral_fan", () -> Items.DEAD_BUBBLE_CORAL_FAN),
	DEAD_BUSH("item/dead_bush", () -> Items.DEAD_BUSH),
	DEAD_FIRE_CORAL("item/dead_fire_coral", () -> Items.DEAD_FIRE_CORAL),
	DEAD_FIRE_CORAL_BLOCK("item/dead_fire_coral_block", () -> Items.DEAD_FIRE_CORAL_BLOCK),
	DEAD_FIRE_CORAL_FAN("item/dead_fire_coral_fan", () -> Items.DEAD_FIRE_CORAL_FAN),
	DEAD_HORN_CORAL("item/dead_horn_coral", () -> Items.DEAD_HORN_CORAL),
	DEAD_HORN_CORAL_BLOCK("item/dead_horn_coral_block", () -> Items.DEAD_HORN_CORAL_BLOCK),
	DEAD_HORN_CORAL_FAN("item/dead_horn_coral_fan", () -> Items.DEAD_HORN_CORAL_FAN),
	DEAD_TUBE_CORAL("item/dead_tube_coral", () -> Items.DEAD_TUBE_CORAL),
	DEAD_TUBE_CORAL_BLOCK("item/dead_tube_coral_block", () -> Items.DEAD_TUBE_CORAL_BLOCK),
	DEAD_TUBE_CORAL_FAN("item/dead_tube_coral_fan", () -> Items.DEAD_TUBE_CORAL_FAN),
	DEBUG_STICK("item/debug_stick", () -> Items.DEBUG_STICK),
	DETECTOR_RAIL("item/detector_rail", () -> Items.DETECTOR_RAIL), DIAMOND("item/diamond", () -> Items.DIAMOND),
	DIAMOND_AXE("item/diamond_axe", () -> Items.DIAMOND_AXE),
	DIAMOND_BLOCK("item/diamond_block", () -> Items.DIAMOND_BLOCK),
	DIAMOND_BOOTS("item/diamond_boots", () -> Items.DIAMOND_BOOTS),
	DIAMOND_CHESTPLATE("item/diamond_chestplate", () -> Items.DIAMOND_CHESTPLATE),
	DIAMOND_HELMET("item/diamond_helmet", () -> Items.DIAMOND_HELMET),
	DIAMOND_HOE("item/diamond_hoe", () -> Items.DIAMOND_HOE),
	DIAMOND_HORSE_ARMOR("item/diamond_horse_armor", () -> Items.DIAMOND_HORSE_ARMOR),
	DIAMOND_LEGGINGS("item/diamond_leggings", () -> Items.DIAMOND_LEGGINGS),
	DIAMOND_ORE("item/diamond_ore", () -> Items.DIAMOND_ORE),
	DIAMOND_PICKAXE("item/diamond_pickaxe", () -> Items.DIAMOND_PICKAXE),
	DIAMOND_SHOVEL("item/diamond_shovel", () -> Items.DIAMOND_SHOVEL),
	DIAMOND_SWORD("item/diamond_sword", () -> Items.DIAMOND_SWORD), DIORITE("item/diorite", () -> Items.DIORITE),
	DIORITE_SLAB("item/diorite_slab", () -> Items.DIORITE_SLAB),
	DIORITE_STAIRS("item/diorite_stairs", () -> Items.DIORITE_STAIRS),
	DIORITE_WALL("item/diorite_wall", () -> Items.DIORITE_WALL), DIRT("item/dirt", () -> Items.DIRT),
	DISPENSER("item/dispenser", () -> Items.DISPENSER),
	DOLPHIN_SPAWN_EGG("item/dolphin_spawn_egg", () -> Items.DOLPHIN_SPAWN_EGG),
	DONKEY_SPAWN_EGG("item/donkey_spawn_egg", () -> Items.DONKEY_SPAWN_EGG),
	DRAGON_BREATH("item/dragon_breath", () -> Items.DRAGON_BREATH),
	DRAGON_EGG("item/dragon_egg", () -> Items.DRAGON_EGG), DRAGON_HEAD("item/dragon_head", () -> Items.DRAGON_HEAD),
	DRIED_KELP("item/dried_kelp", () -> Items.DRIED_KELP),
	DRIED_KELP_BLOCK("item/dried_kelp_block", () -> Items.DRIED_KELP_BLOCK),
	DROPPER("item/dropper", () -> Items.DROPPER),
	DROWNED_SPAWN_EGG("item/drowned_spawn_egg", () -> Items.DROWNED_SPAWN_EGG), EGG("item/egg", () -> Items.EGG),
	ELDER_GUARDIAN_SPAWN_EGG("item/elder_guardian_spawn_egg", () -> Items.ELDER_GUARDIAN_SPAWN_EGG),
	ELYTRA("item/elytra", () -> Items.ELYTRA), EMERALD("item/emerald", () -> Items.EMERALD),
	EMERALD_BLOCK("item/emerald_block", () -> Items.EMERALD_BLOCK),
	EMERALD_ORE("item/emerald_ore", () -> Items.EMERALD_ORE),
	ENCHANTED_BOOK("item/enchanted_book", () -> Items.ENCHANTED_BOOK),
	ENCHANTED_GOLDEN_APPLE("item/enchanted_golden_apple", () -> Items.ENCHANTED_GOLDEN_APPLE),
	ENCHANTING_TABLE("item/enchanting_table", () -> Items.ENCHANTING_TABLE),
	END_CRYSTAL("item/end_crystal", () -> Items.END_CRYSTAL),
	END_PORTAL_FRAME("item/end_portal_frame", () -> Items.END_PORTAL_FRAME),
	END_ROD("item/end_rod", () -> Items.END_ROD), END_STONE("item/end_stone", () -> Items.END_STONE),
	END_STONE_BRICK_SLAB("item/end_stone_brick_slab", () -> Items.END_STONE_BRICK_SLAB),
	END_STONE_BRICK_STAIRS("item/end_stone_brick_stairs", () -> Items.END_STONE_BRICK_STAIRS),
	END_STONE_BRICK_WALL("item/end_stone_brick_wall", () -> Items.END_STONE_BRICK_WALL),
	END_STONE_BRICKS("item/end_stone_bricks", () -> Items.END_STONE_BRICKS),
	ENDER_CHEST("item/ender_chest", () -> Items.ENDER_CHEST), ENDER_EYE("item/ender_eye", () -> Items.ENDER_EYE),
	ENDER_PEARL("item/ender_pearl", () -> Items.ENDER_PEARL),
	ENDERMAN_SPAWN_EGG("item/enderman_spawn_egg", () -> Items.ENDERMAN_SPAWN_EGG),
	ENDERMITE_SPAWN_EGG("item/endermite_spawn_egg", () -> Items.ENDERMITE_SPAWN_EGG),
	EVOKER_SPAWN_EGG("item/evoker_spawn_egg", () -> Items.EVOKER_SPAWN_EGG),
	EXPERIENCE_BOTTLE("item/experience_bottle", () -> Items.EXPERIENCE_BOTTLE),
	FARMLAND("item/farmland", () -> Items.FARMLAND), FEATHER("item/feather", () -> Items.FEATHER),
	FERMENTED_SPIDER_EYE("item/fermented_spider_eye", () -> Items.FERMENTED_SPIDER_EYE),
	FERN("item/fern", () -> Items.FERN), FILLED_MAP("item/filled_map", () -> Items.FILLED_MAP),
	FIRE_CHARGE("item/fire_charge", () -> Items.FIRE_CHARGE), FIRE_CORAL("item/fire_coral", () -> Items.FIRE_CORAL),
	FIRE_CORAL_BLOCK("item/fire_coral_block", () -> Items.FIRE_CORAL_BLOCK),
	FIRE_CORAL_FAN("item/fire_coral_fan", () -> Items.FIRE_CORAL_FAN),
	FIREWORK_ROCKET("item/firework_rocket", () -> Items.FIREWORK_ROCKET),
	FIREWORK_STAR("item/firework_star", () -> Items.FIREWORK_STAR),
	FISHING_ROD("item/fishing_rod", () -> Items.FISHING_ROD),
	FLETCHING_TABLE("item/fletching_table", () -> Items.FLETCHING_TABLE), FLINT("item/flint", () -> Items.FLINT),
	FLINT_AND_STEEL("item/flint_and_steel", () -> Items.FLINT_AND_STEEL),
	FLOWER_BANNER_PATTERN("item/flower_banner_pattern", () -> Items.FLOWER_BANNER_PATTERN),
	FLOWER_POT("item/flower_pot", () -> Items.FLOWER_POT),
	FOX_SPAWN_EGG("item/fox_spawn_egg", () -> Items.FOX_SPAWN_EGG), FURNACE("item/furnace", () -> Items.FURNACE),
	FURNACE_MINECART("item/furnace_minecart", () -> Items.FURNACE_MINECART),
	GHAST_SPAWN_EGG("item/ghast_spawn_egg", () -> Items.GHAST_SPAWN_EGG),
	GHAST_TEAR("item/ghast_tear", () -> Items.GHAST_TEAR),
	GILDED_BLACKSTONE("item/gilded_blackstone", () -> Items.GILDED_BLACKSTONE), GLASS("item/glass", () -> Items.GLASS),
	GLASS_BOTTLE("item/glass_bottle", () -> Items.GLASS_BOTTLE), GLASS_PANE("item/glass_pane", () -> Items.GLASS_PANE),
	GLISTERING_MELON_SLICE("item/glistering_melon_slice", () -> Items.GLISTERING_MELON_SLICE),
	GLOBE_BANNER_PATTERN("item/globe_banner_pattern", () -> Items.GLOBE_BANNER_PATTER),
	GLOWSTONE("item/glowstone", () -> Items.GLOWSTONE),
	GLOWSTONE_DUST("item/glowstone_dust", () -> Items.GLOWSTONE_DUST),
	GOLD_BLOCK("item/gold_block", () -> Items.GOLD_BLOCK), GOLD_INGOT("item/gold_ingot", () -> Items.GOLD_INGOT),
	GOLD_NUGGET("item/gold_nugget", () -> Items.GOLD_NUGGET), GOLD_ORE("item/gold_ore", () -> Items.GOLD_ORE),
	GOLDEN_APPLE("item/golden_apple", () -> Items.GOLDEN_APPLE), GOLDEN_AXE("item/golden_axe", () -> Items.GOLDEN_AXE),
	GOLDEN_BOOTS("item/golden_boots", () -> Items.GOLDEN_BOOTS),
	GOLDEN_CARROT("item/golden_carrot", () -> Items.GOLDEN_CARROT),
	GOLDEN_CHESTPLATE("item/golden_chestplate", () -> Items.GOLDEN_CHESTPLATE),
	GOLDEN_HELMET("item/golden_helmet", () -> Items.GOLDEN_HELMET),
	GOLDEN_HOE("item/golden_hoe", () -> Items.GOLDEN_HOE),
	GOLDEN_HORSE_ARMOR("item/golden_horse_armor", () -> Items.GOLDEN_HORSE_ARMOR),
	GOLDEN_LEGGINGS("item/golden_leggings", () -> Items.GOLDEN_LEGGINGS),
	GOLDEN_PICKAXE("item/golden_pickaxe", () -> Items.GOLDEN_PICKAXE),
	GOLDEN_SHOVEL("item/golden_shovel", () -> Items.GOLDEN_SHOVEL),
	GOLDEN_SWORD("item/golden_sword", () -> Items.GOLDEN_SWORD), GRANITE("item/granite", () -> Items.GRANITE),
	GRANITE_SLAB("item/granite_slab", () -> Items.GRANITE_SLAB),
	GRANITE_STAIRS("item/granite_stairs", () -> Items.GRANITE_STAIRS),
	GRANITE_WALL("item/granite_wall", () -> Items.GRANITE_WALL), GRASS("item/grass", () -> Items.GRASS),
	GRASS_BLOCK("item/grass_block", () -> Items.GRASS_BLOCK), GRASS_PATH("item/grass_path", () -> Items.GRASS_PATH),
	GRAVEL("item/gravel", () -> Items.GRAVEL), GRAY_BANNER("item/gray_banner", () -> Items.GRAY_BANNER),
	GRAY_BED("item/gray_bed", () -> Items.GRAY_BED), GRAY_CARPET("item/gray_carpet", () -> Items.GRAY_CARPET),
	GRAY_CONCRETE("item/gray_concrete", () -> Items.GRAY_CONCRETE),
	GRAY_CONCRETE_POWDER("item/gray_concrete_powder", () -> Items.GRAY_CONCRETE_POWDER),
	GRAY_DYE("item/gray_dye", () -> Items.GRAY_DYE),
	GRAY_GLAZED_TERRACOTTA("item/gray_glazed_terracotta", () -> Items.GRAY_GLAZED_TERRACOTTA),
	GRAY_SHULKER_BOX("item/gray_shulker_box", () -> Items.GRAY_SHULKER_BOX),
	GRAY_STAINED_GLASS("item/gray_stained_glass", () -> Items.GRAY_STAINED_GLASS),
	GRAY_STAINED_GLASS_PANE("item/gray_stained_glass_pane", () -> Items.GRAY_STAINED_GLASS_PANE),
	GRAY_TERRACOTTA("item/gray_terracotta", () -> Items.GRAY_TERRACOTTA),
	GRAY_WOOL("item/gray_wool", () -> Items.GRAY_WOOL), GREEN_BANNER("item/green_banner", () -> Items.GREEN_BANNER),
	GREEN_BED("item/green_bed", () -> Items.GREEN_BED), GREEN_CARPET("item/green_carpet", () -> Items.GREEN_CARPET),
	GREEN_CONCRETE("item/green_concrete", () -> Items.GREEN_CONCRETE),
	GREEN_CONCRETE_POWDER("item/green_concrete_powder", () -> Items.GREEN_CONCRETE_POWDER),
	GREEN_DYE("item/green_dye", () -> Items.GREEN_DYE),
	GREEN_GLAZED_TERRACOTTA("item/green_glazed_terracotta", () -> Items.GREEN_GLAZED_TERRACOTTA),
	GREEN_SHULKER_BOX("item/green_shulker_box", () -> Items.GREEN_SHULKER_BOX),
	GREEN_STAINED_GLASS("item/green_stained_glass", () -> Items.GREEN_STAINED_GLASS),
	GREEN_STAINED_GLASS_PANE("item/green_stained_glass_pane", () -> Items.GREEN_STAINED_GLASS_PANE),
	GREEN_TERRACOTTA("item/green_terracotta", () -> Items.GREEN_TERRACOTTA),
	GREEN_WOOL("item/green_wool", () -> Items.GREEN_WOOL), GRINDSTONE("item/grindstone", () -> Items.GRINDSTONE),
	GUARDIAN_SPAWN_EGG("item/guardian_spawn_egg", () -> Items.GUARDIAN_SPAWN_EGG),
	GUNPOWDER("item/gunpowder", () -> Items.GUNPOWDER), HAY_BLOCK("item/hay_block", () -> Items.HAY_BLOCK),
	HEART_OF_THE_SEA("item/heart_of_the_sea", () -> Items.HEART_OF_THE_SEA),
	HEAVY_WEIGHTED_PRESSURE_PLATE("item/heavy_weighted_pressure_plate", () -> Items.HEAVY_WEIGHTED_PRESSURE_PLATE),
	HOGLIN_SPAWN_EGG("item/hoglin_spawn_egg", () -> Items.HOGLIN_SPAWN_EGG),
	HONEY_BLOCK("item/honey_block", () -> Items.HONEY_BLOCK),
	HONEY_BOTTLE("item/honey_bottle", () -> Items.HONEY_BOTTLE), HONEYCOMB("item/honeycomb", () -> Items.HONEYCOMB),
	HONEYCOMB_BLOCK("item/honeycomb_block", () -> Items.HONEYCOMB_BLOCK), HOPPER("item/hopper", () -> Items.HOPPER),
	HOPPER_MINECART("item/hopper_minecart", () -> Items.HOPPER_MINECART),
	HORN_CORAL("item/horn_coral", () -> Items.HORN_CORAL),
	HORN_CORAL_BLOCK("item/horn_coral_block", () -> Items.HORN_CORAL_BLOCK),
	HORN_CORAL_FAN("item/horn_coral_fan", () -> Items.HORN_CORAL_FAN),
	HORSE_SPAWN_EGG("item/horse_spawn_egg", () -> Items.HORSE_SPAWN_EGG),
	HUSK_SPAWN_EGG("item/husk_spawn_egg", () -> Items.HUSK_SPAWN_EGG), ICE("item/ice", () -> Items.ICE),
	INFESTED_CHISELED_STONE_BRICKS("item/infested_chiseled_stone_bricks", () -> Items.INFESTED_CHISELED_STONE_BRICKS),
	INFESTED_COBBLESTONE("item/infested_cobblestone", () -> Items.INFESTED_COBBLESTONE),
	INFESTED_CRACKED_STONE_BRICKS("item/infested_cracked_stone_bricks", () -> Items.INFESTED_CRACKED_STONE_BRICKS),
	INFESTED_MOSSY_STONE_BRICKS("item/infested_mossy_stone_bricks", () -> Items.INFESTED_MOSSY_STONE_BRICKS),
	INFESTED_STONE("item/infested_stone", () -> Items.INFESTED_STONE),
	INFESTED_STONE_BRICKS("item/infested_stone_bricks", () -> Items.INFESTED_STONE_BRICKS),
	INK_SAC("item/ink_sac", () -> Items.INK_SAC), IRON_AXE("item/iron_axe", () -> Items.IRON_AXE),
	IRON_BARS("item/iron_bars", () -> Items.IRON_BARS), IRON_BLOCK("item/iron_block", () -> Items.IRON_BLOCK),
	IRON_BOOTS("item/iron_boots", () -> Items.IRON_BOOTS),
	IRON_CHESTPLATE("item/iron_chestplate", () -> Items.IRON_CHESTPLATE),
	IRON_DOOR("item/iron_door", () -> Items.IRON_DOOR), IRON_HELMET("item/iron_helmet", () -> Items.IRON_HELMET),
	IRON_HOE("item/iron_hoe", () -> Items.IRON_HOE),
	IRON_HORSE_ARMOR("item/iron_horse_armor", () -> Items.IRON_HORSE_ARMOR),
	IRON_INGOT("item/iron_ingot", () -> Items.IRON_INGOT),
	IRON_LEGGINGS("item/iron_leggings", () -> Items.IRON_LEGGINGS),
	IRON_NUGGET("item/iron_nugget", () -> Items.IRON_NUGGET), IRON_ORE("item/iron_ore", () -> Items.IRON_ORE),
	IRON_PICKAXE("item/iron_pickaxe", () -> Items.IRON_PICKAXE),
	IRON_SHOVEL("item/iron_shovel", () -> Items.IRON_SHOVEL), IRON_SWORD("item/iron_sword", () -> Items.IRON_SWORD),
	IRON_TRAPDOOR("item/iron_trapdoor", () -> Items.IRON_TRAPDOOR),
	ITEM_FRAME("item/item_frame", () -> Items.ITEM_FRAME),
	JACK_O_LANTERN("item/jack_o_lantern", () -> Items.JACK_O_LANTERN), JIGSAW("item/jigsaw", () -> Items.JIGSAW),
	JUKEBOX("item/jukebox", () -> Items.JUKEBOX), JUNGLE_BOAT("item/jungle_boat", () -> Items.JUNGLE_BOAT),
	JUNGLE_BUTTON("item/jungle_button", () -> Items.JUNGLE_BUTTON),
	JUNGLE_DOOR("item/jungle_door", () -> Items.JUNGLE_DOOR),
	JUNGLE_FENCE("item/jungle_fence", () -> Items.JUNGLE_FENCE),
	JUNGLE_FENCE_GATE("item/jungle_fence_gate", () -> Items.JUNGLE_FENCE_GATE),
	JUNGLE_LEAVES("item/jungle_leaves", () -> Items.JUNGLE_LEAVES),
	JUNGLE_LOG("item/jungle_log", () -> Items.JUNGLE_LOG),
	JUNGLE_PLANKS("item/jungle_planks", () -> Items.JUNGLE_PLANKS),
	JUNGLE_PRESSURE_PLATE("item/jungle_pressure_plate", () -> Items.JUNGLE_PRESSURE_PLATE),
	JUNGLE_SAPLING("item/jungle_sapling", () -> Items.JUNGLE_SAPLING),
	JUNGLE_SIGN("item/jungle_sign", () -> Items.JUNGLE_SIGN), JUNGLE_SLAB("item/jungle_slab", () -> Items.JUNGLE_SLAB),
	JUNGLE_STAIRS("item/jungle_stairs", () -> Items.JUNGLE_STAIRS),
	JUNGLE_TRAPDOOR("item/jungle_trapdoor", () -> Items.JUNGLE_TRAPDOOR),
	JUNGLE_WOOD("item/jungle_wood", () -> Items.JUNGLE_WOOD), KELP("item/kelp", () -> Items.KELP),
	KNOWLEDGE_BOOK("item/knowledge_book", () -> Items.KNOWLEDGE_BOOK), LADDER("item/ladder", () -> Items.LADDER),
	LANTERN("item/lantern", () -> Items.LANTERN), LAPIS_BLOCK("item/lapis_block", () -> Items.LAPIS_BLOCK),
	LAPIS_LAZULI("item/lapis_lazuli", () -> Items.LAPIS_LAZULI), LAPIS_ORE("item/lapis_ore", () -> Items.LAPIS_ORE),
	LARGE_FERN("item/large_fern", () -> Items.LARGE_FERN), LAVA_BUCKET("item/lava_bucket", () -> Items.LAVA_BUCKET),
	LEAD("item/lead", () -> Items.LEAD), LEATHER("item/leather", () -> Items.LEATHER),
	LEATHER_BOOTS("item/leather_boots", () -> Items.LEATHER_BOOTS),
	LEATHER_CHESTPLATE("item/leather_chestplate", () -> Items.LEATHER_CHESTPLATE),
	LEATHER_HELMET("item/leather_helmet", () -> Items.LEATHER_HELMET),
	LEATHER_HORSE_ARMOR("item/leather_horse_armor", () -> Items.LEATHER_HORSE_ARMOR),
	LEATHER_LEGGINGS("item/leather_leggings", () -> Items.LEATHER_LEGGINGS),
	LECTERN("item/lectern", () -> Items.LECTERN), LEVER("item/lever", () -> Items.LEVER),
	LIGHT_BLUE_BANNER("item/light_blue_banner", () -> Items.LIGHT_BLUE_BANNER),
	LIGHT_BLUE_BED("item/light_blue_bed", () -> Items.LIGHT_BLUE_BED),
	LIGHT_BLUE_CARPET("item/light_blue_carpet", () -> Items.LIGHT_BLUE_CARPET),
	LIGHT_BLUE_CONCRETE("item/light_blue_concrete", () -> Items.LIGHT_BLUE_CONCRETE),
	LIGHT_BLUE_CONCRETE_POWDER("item/light_blue_concrete_powder", () -> Items.LIGHT_BLUE_CONCRETE_POWDER),
	LIGHT_BLUE_DYE("item/light_blue_dye", () -> Items.LIGHT_BLUE_DYE),
	LIGHT_BLUE_GLAZED_TERRACOTTA("item/light_blue_glazed_terracotta", () -> Items.LIGHT_BLUE_GLAZED_TERRACOTTA),
	LIGHT_BLUE_SHULKER_BOX("item/light_blue_shulker_box", () -> Items.LIGHT_BLUE_SHULKER_BOX),
	LIGHT_BLUE_STAINED_GLASS("item/light_blue_stained_glass", () -> Items.LIGHT_BLUE_STAINED_GLASS),
	LIGHT_BLUE_STAINED_GLASS_PANE("item/light_blue_stained_glass_pane", () -> Items.LIGHT_BLUE_STAINED_GLASS_PANE),
	LIGHT_BLUE_TERRACOTTA("item/light_blue_terracotta", () -> Items.LIGHT_BLUE_TERRACOTTA),
	LIGHT_BLUE_WOOL("item/light_blue_wool", () -> Items.LIGHT_BLUE_WOOL),
	LIGHT_GRAY_BANNER("item/light_gray_banner", () -> Items.LIGHT_GRAY_BANNER),
	LIGHT_GRAY_BED("item/light_gray_bed", () -> Items.LIGHT_GRAY_BED),
	LIGHT_GRAY_CARPET("item/light_gray_carpet", () -> Items.LIGHT_GRAY_CARPET),
	LIGHT_GRAY_CONCRETE("item/light_gray_concrete", () -> Items.LIGHT_GRAY_CONCRETE),
	LIGHT_GRAY_CONCRETE_POWDER("item/light_gray_concrete_powder", () -> Items.LIGHT_GRAY_CONCRETE_POWDER),
	LIGHT_GRAY_DYE("item/light_gray_dye", () -> Items.LIGHT_GRAY_DYE),
	LIGHT_GRAY_GLAZED_TERRACOTTA("item/light_gray_glazed_terracotta", () -> Items.LIGHT_GRAY_GLAZED_TERRACOTTA),
	LIGHT_GRAY_SHULKER_BOX("item/light_gray_shulker_box", () -> Items.LIGHT_GRAY_SHULKER_BOX),
	LIGHT_GRAY_STAINED_GLASS("item/light_gray_stained_glass", () -> Items.LIGHT_GRAY_STAINED_GLASS),
	LIGHT_GRAY_STAINED_GLASS_PANE("item/light_gray_stained_glass_pane", () -> Items.LIGHT_GRAY_STAINED_GLASS_PANE),
	LIGHT_GRAY_TERRACOTTA("item/light_gray_terracotta", () -> Items.LIGHT_GRAY_TERRACOTTA),
	LIGHT_GRAY_WOOL("item/light_gray_wool", () -> Items.LIGHT_GRAY_WOOL),
	LIGHT_WEIGHTED_PRESSURE_PLATE("item/light_weighted_pressure_plate", () -> Items.LIGHT_WEIGHTED_PRESSURE_PLATE),
	LILAC("item/lilac", () -> Items.LILAC),
	LILY_OF_THE_VALLEY("item/lily_of_the_valley", () -> Items.LILY_OF_THE_VALLEY),
	LILY_PAD("item/lily_pad", () -> Items.LILY_PAD), LIME_BANNER("item/lime_banner", () -> Items.LIME_BANNER),
	LIME_BED("item/lime_bed", () -> Items.LIME_BED), LIME_CARPET("item/lime_carpet", () -> Items.LIME_CARPET),
	LIME_CONCRETE("item/lime_concrete", () -> Items.LIME_CONCRETE),
	LIME_CONCRETE_POWDER("item/lime_concrete_powder", () -> Items.LIME_CONCRETE_POWDER),
	LIME_DYE("item/lime_dye", () -> Items.LIME_DYE),
	LIME_GLAZED_TERRACOTTA("item/lime_glazed_terracotta", () -> Items.LIME_GLAZED_TERRACOTTA),
	LIME_SHULKER_BOX("item/lime_shulker_box", () -> Items.LIME_SHULKER_BOX),
	LIME_STAINED_GLASS("item/lime_stained_glass", () -> Items.LIME_STAINED_GLASS),
	LIME_STAINED_GLASS_PANE("item/lime_stained_glass_pane", () -> Items.LIME_STAINED_GLASS_PANE),
	LIME_TERRACOTTA("item/lime_terracotta", () -> Items.LIME_TERRACOTTA),
	LIME_WOOL("item/lime_wool", () -> Items.LIME_WOOL),
	LINGERING_POTION("item/lingering_potion", () -> Items.LINGERING_POTION),
	LLAMA_SPAWN_EGG("item/llama_spawn_egg", () -> Items.LLAMA_SPAWN_EGG),
	LODESTONE("item/lodestone", () -> Items.LODESTONE), LOOM("item/loom", () -> Items.LOOM),
	MAGENTA_BANNER("item/magenta_banner", () -> Items.MAGENTA_BANNER),
	MAGENTA_BED("item/magenta_bed", () -> Items.MAGENTA_BED),
	MAGENTA_CARPET("item/magenta_carpet", () -> Items.MAGENTA_CARPET),
	MAGENTA_CONCRETE("item/magenta_concrete", () -> Items.MAGENTA_CONCRETE),
	MAGENTA_CONCRETE_POWDER("item/magenta_concrete_powder", () -> Items.MAGENTA_CONCRETE_POWDER),
	MAGENTA_DYE("item/magenta_dye", () -> Items.MAGENTA_DYE),
	MAGENTA_GLAZED_TERRACOTTA("item/magenta_glazed_terracotta", () -> Items.MAGENTA_GLAZED_TERRACOTTA),
	MAGENTA_SHULKER_BOX("item/magenta_shulker_box", () -> Items.MAGENTA_SHULKER_BOX),
	MAGENTA_STAINED_GLASS("item/magenta_stained_glass", () -> Items.MAGENTA_STAINED_GLASS),
	MAGENTA_STAINED_GLASS_PANE("item/magenta_stained_glass_pane", () -> Items.MAGENTA_STAINED_GLASS_PANE),
	MAGENTA_TERRACOTTA("item/magenta_terracotta", () -> Items.MAGENTA_TERRACOTTA),
	MAGENTA_WOOL("item/magenta_wool", () -> Items.MAGENTA_WOOL),
	MAGMA_BLOCK("item/magma_block", () -> Items.MAGMA_BLOCK), MAGMA_CREAM("item/magma_cream", () -> Items.MAGMA_CREAM),
	MAGMA_CUBE_SPAWN_EGG("item/magma_cube_spawn_egg", () -> Items.MAGMA_CUBE_SPAWN_EGG),
	MAP("item/map", () -> Items.MAP), MELON("item/melon", () -> Items.MELON),
	MELON_SEEDS("item/melon_seeds", () -> Items.MELON_SEEDS), MELON_SLICE("item/melon_slice", () -> Items.MELON_SLICE),
	MILK_BUCKET("item/milk_bucket", () -> Items.MILK_BUCKET), MINECART("item/minecart", () -> Items.MINECART),
	MOJANG_BANNER_PATTERN("item/mojang_banner_pattern", () -> Items.MOJANG_BANNER_PATTERN),
	MOOSHROOM_SPAWN_EGG("item/mooshroom_spawn_egg", () -> Items.MOOSHROOM_SPAWN_EGG),
	MOSSY_COBBLESTONE("item/mossy_cobblestone", () -> Items.MOSSY_COBBLESTONE),
	MOSSY_COBBLESTONE_SLAB("item/mossy_cobblestone_slab", () -> Items.MOSSY_COBBLESTONE_SLAB),
	MOSSY_COBBLESTONE_STAIRS("item/mossy_cobblestone_stairs", () -> Items.MOSSY_COBBLESTONE_STAIRS),
	MOSSY_COBBLESTONE_WALL("item/mossy_cobblestone_wall", () -> Items.MOSSY_COBBLESTONE_WALL),
	MOSSY_STONE_BRICK_SLAB("item/mossy_stone_brick_slab", () -> Items.MOSSY_STONE_BRICK_SLAB),
	MOSSY_STONE_BRICK_STAIRS("item/mossy_stone_brick_stairs", () -> Items.MOSSY_STONE_BRICK_STAIRS),
	MOSSY_STONE_BRICK_WALL("item/mossy_stone_brick_wall", () -> Items.MOSSY_STONE_BRICK_WALL),
	MOSSY_STONE_BRICKS("item/mossy_stone_bricks", () -> Items.MOSSY_STONE_BRICKS),
	MULE_SPAWN_EGG("item/mule_spawn_egg", () -> Items.MULE_SPAWN_EGG),
	MUSHROOM_STEM("item/mushroom_stem", () -> Items.MUSHROOM_STEM),
	MUSHROOM_STEW("item/mushroom_stew", () -> Items.MUSHROOM_STEW),
	MUSIC_DISC_11("item/music_disc_11", () -> Items.MUSIC_DISC_11),
	MUSIC_DISC_13("item/music_disc_13", () -> Items.MUSIC_DISC_13),
	MUSIC_DISC_BLOCKS("item/music_disc_blocks", () -> Items.MUSIC_DISC_BLOCKS),
	MUSIC_DISC_CAT("item/music_disc_cat", () -> Items.MUSIC_DISC_CAT),
	MUSIC_DISC_CHIRP("item/music_disc_chirp", () -> Items.MUSIC_DISC_CHIRP),
	MUSIC_DISC_FAR("item/music_disc_far", () -> Items.MUSIC_DISC_FAR),
	MUSIC_DISC_MALL("item/music_disc_mall", () -> Items.MUSIC_DISC_MALL),
	MUSIC_DISC_MELLOHI("item/music_disc_mellohi", () -> Items.MUSIC_DISC_MELLOHI),
	MUSIC_DISC_PIGSTEP("item/music_disc_pigstep", () -> Items.MUSIC_DISC_PIGSTEP),
	MUSIC_DISC_STAL("item/music_disc_stal", () -> Items.MUSIC_DISC_STAL),
	MUSIC_DISC_STRAD("item/music_disc_strad", () -> Items.MUSIC_DISC_STRAD),
	MUSIC_DISC_WAIT("item/music_disc_wait", () -> Items.MUSIC_DISC_WAIT),
	MUSIC_DISC_WARD("item/music_disc_ward", () -> Items.MUSIC_DISC_WARD), MUTTON("item/mutton", () -> Items.MUTTON),
	MYCELIUM("item/mycelium", () -> Items.MYCELIUM), NAME_TAG("item/name_tag", () -> Items.NAME_TAG),
	NAUTILUS_SHELL("item/nautilus_shell", () -> Items.NAUTILUS_SHELL),
	NETHER_BRICK("item/nether_brick", () -> Items.NETHER_BRICK),
	NETHER_BRICK_FENCE("item/nether_brick_fence", () -> Items.NETHER_BRICK_FENCE),
	NETHER_BRICK_SLAB("item/nether_brick_slab", () -> Items.NETHER_BRICK_SLAB),
	NETHER_BRICK_STAIRS("item/nether_brick_stairs", () -> Items.NETHER_BRICK_STAIRS),
	NETHER_BRICK_WALL("item/nether_brick_wall", () -> Items.NETHER_BRICK_WALL),
	NETHER_BRICKS("item/nether_bricks", () -> Items.NETHER_BRICKS),
	NETHER_GOLD_ORE("item/nether_gold_ore", () -> Items.NETHER_GOLD_ORE),
	NETHER_QUARTZ_ORE("item/nether_quartz_ore", () -> Items.NETHER_QUARTZ_ORE),
	NETHER_SPROUTS("item/nether_sprouts", () -> Items.NETHER_SPROUTS),
	NETHER_STAR("item/nether_star", () -> Items.NETHER_STAR), NETHER_WART("item/nether_wart", () -> Items.NETHER_WART),
	NETHER_WART_BLOCK("item/nether_wart_block", () -> Items.NETHER_WART_BLOCK),
	NETHERITE_AXE("item/netherite_axe", () -> Items.NETHERITE_AXE),
	NETHERITE_BLOCK("item/netherite_block", () -> Items.NETHERITE_BLOCK),
	NETHERITE_BOOTS("item/netherite_boots", () -> Items.NETHERITE_BOOTS),
	NETHERITE_CHESTPLATE("item/netherite_chestplate", () -> Items.NETHERITE_CHESTPLATE),
	NETHERITE_HELMET("item/netherite_helmet", () -> Items.NETHERITE_HELMET),
	NETHERITE_HOE("item/netherite_hoe", () -> Items.NETHERITE_HOE),
	NETHERITE_INGOT("item/netherite_ingot", () -> Items.NETHERITE_INGOT),
	NETHERITE_LEGGINGS("item/netherite_leggings", () -> Items.NETHERITE_LEGGINGS),
	NETHERITE_PICKAXE("item/netherite_pickaxe", () -> Items.NETHERITE_PICKAXE),
	NETHERITE_SCRAP("item/netherite_scrap", () -> Items.NETHERITE_SCRAP),
	NETHERITE_SHOVEL("item/netherite_shovel", () -> Items.NETHERITE_SHOVEL),
	NETHERITE_SWORD("item/netherite_sword", () -> Items.NETHERITE_SWORD),
	NETHERRACK("item/netherrack", () -> Items.NETHERRACK), NOTE_BLOCK("item/note_block", () -> Items.NOTE_BLOCK),
	OAK_BOAT("item/oak_boat", () -> Items.OAK_BOAT), OAK_BUTTON("item/oak_button", () -> Items.OAK_BUTTON),
	OAK_DOOR("item/oak_door", () -> Items.OAK_DOOR), OAK_FENCE("item/oak_fence", () -> Items.OAK_FENCE),
	OAK_FENCE_GATE("item/oak_fence_gate", () -> Items.OAK_FENCE_GATE),
	OAK_LEAVES("item/oak_leaves", () -> Items.OAK_LEAVES), OAK_LOG("item/oak_log", () -> Items.OAK_LOG),
	OAK_PLANKS("item/oak_planks", () -> Items.OAK_PLANKS),
	OAK_PRESSURE_PLATE("item/oak_pressure_plate", () -> Items.OAK_PRESSURE_PLATE),
	OAK_SAPLING("item/oak_sapling", () -> Items.OAK_SAPLING), OAK_SIGN("item/oak_sign", () -> Items.OAK_SIGN),
	OAK_SLAB("item/oak_slab", () -> Items.OAK_SLAB), OAK_STAIRS("item/oak_stairs", () -> Items.OAK_STAIRS),
	OAK_TRAPDOOR("item/oak_trapdoor", () -> Items.OAK_TRAPDOOR), OAK_WOOD("item/oak_wood", () -> Items.OAK_WOOD),
	OBSERVER("item/observer", () -> Items.OBSERVER), OBSIDIAN("item/obsidian", () -> Items.OBSIDIAN),
	OCELOT_SPAWN_EGG("item/ocelot_spawn_egg", () -> Items.OCELOT_SPAWN_EGG),
	ORANGE_BANNER("item/orange_banner", () -> Items.ORANGE_BANNER),
	ORANGE_BED("item/orange_bed", () -> Items.ORANGE_BED),
	ORANGE_CARPET("item/orange_carpet", () -> Items.ORANGE_CARPET),
	ORANGE_CONCRETE("item/orange_concrete", () -> Items.ORANGE_CONCRETE),
	ORANGE_CONCRETE_POWDER("item/orange_concrete_powder", () -> Items.ORANGE_CONCRETE_POWDER),
	ORANGE_DYE("item/orange_dye", () -> Items.ORANGE_DYE),
	ORANGE_GLAZED_TERRACOTTA("item/orange_glazed_terracotta", () -> Items.ORANGE_GLAZED_TERRACOTTA),
	ORANGE_SHULKER_BOX("item/orange_shulker_box", () -> Items.ORANGE_SHULKER_BOX),
	ORANGE_STAINED_GLASS("item/orange_stained_glass", () -> Items.ORANGE_STAINED_GLASS),
	ORANGE_STAINED_GLASS_PANE("item/orange_stained_glass_pane", () -> Items.ORANGE_STAINED_GLASS_PANE),
	ORANGE_TERRACOTTA("item/orange_terracotta", () -> Items.ORANGE_TERRACOTTA),
	ORANGE_TULIP("item/orange_tulip", () -> Items.ORANGE_TULIP),
	ORANGE_WOOL("item/orange_wool", () -> Items.ORANGE_WOOL), OXEYE_DAISY("item/oxeye_daisy", () -> Items.OXEYE_DAISY),
	PACKED_ICE("item/packed_ice", () -> Items.PACKED_ICE), PAINTING("item/painting", () -> Items.PAINTING),
	PANDA_SPAWN_EGG("item/panda_spawn_egg", () -> Items.PANDA_SPAWN_EGG), PAPER("item/paper", () -> Items.PAPER),
	PARROT_SPAWN_EGG("item/parrot_spawn_egg", () -> Items.PARROT_SPAWN_EGG), PEONY("item/peony", () -> Items.PEONY),
	PETRIFIED_OAK_SLAB("item/petrified_oak_slab", () -> Items.PETRIFIED_OAK_SLAB),
	PHANTOM_MEMBRANE("item/phantom_membrane", () -> Items.PHANTOM_MEMBRANE),
	PHANTOM_SPAWN_EGG("item/phantom_spawn_egg", () -> Items.PHANTOM_SPAWN_EGG),
	PIG_SPAWN_EGG("item/pig_spawn_egg", () -> Items.PIG_SPAWN_EGG),
	PIGLIN_BANNER_PATTERN("item/piglin_banner_pattern", () -> Items.PIGLIN_BANNER_PATTERN),
	PIGLIN_BRUTE_SPAWN_EGG("item/piglin_brute_spawn_egg", () -> Items.PIGLIN_BRUTE_SPAWN_EGG),
	PIGLIN_SPAWN_EGG("item/piglin_spawn_egg", () -> Items.PIGLIN_SPAWN_EGG),
	PILLAGER_SPAWN_EGG("item/pillager_spawn_egg", () -> Items.PILLAGER_SPAWN_EGG),
	PINK_BANNER("item/pink_banner", () -> Items.PINK_BANNER), PINK_BED("item/pink_bed", () -> Items.PINK_BED),
	PINK_CARPET("item/pink_carpet", () -> Items.PINK_CARPET),
	PINK_CONCRETE("item/pink_concrete", () -> Items.PINK_CONCRETE),
	PINK_CONCRETE_POWDER("item/pink_concrete_powder", () -> Items.PINK_CONCRETE_POWDER),
	PINK_DYE("item/pink_dye", () -> Items.PINK_DYE),
	PINK_GLAZED_TERRACOTTA("item/pink_glazed_terracotta", () -> Items.PINK_GLAZED_TERRACOTTA),
	PINK_SHULKER_BOX("item/pink_shulker_box", () -> Items.PINK_SHULKER_BOX),
	PINK_STAINED_GLASS("item/pink_stained_glass", () -> Items.PINK_STAINED_GLASS),
	PINK_STAINED_GLASS_PANE("item/pink_stained_glass_pane", () -> Items.PINK_STAINED_GLASS_PANE),
	PINK_TERRACOTTA("item/pink_terracotta", () -> Items.PINK_TERRACOTTA),
	PINK_TULIP("item/pink_tulip", () -> Items.PINK_TULIP), PINK_WOOL("item/pink_wool", () -> Items.PINK_WOOL),
	PISTON("item/piston", () -> Items.PISTON), PLAYER_HEAD("item/player_head", () -> Items.PLAYER_HEAD),
	PODZOL("item/podzol", () -> Items.PODZOL), POISONOUS_POTATO("item/poisonous_potato", () -> Items.POISONOUS_POTATO),
	POLAR_BEAR_SPAWN_EGG("item/polar_bear_spawn_egg", () -> Items.POLAR_BEAR_SPAWN_EGG),
	POLISHED_ANDESITE("item/polished_andesite", () -> Items.POLISHED_ANDESITE),
	POLISHED_ANDESITE_SLAB("item/polished_andesite_slab", () -> Items.POLISHED_ANDESITE_SLAB),
	POLISHED_ANDESITE_STAIRS("item/polished_andesite_stairs", () -> Items.POLISHED_ANDESITE_STAIRS),
	POLISHED_BASALT("item/polished_basalt", () -> Items.POLISHED_BASALT),
	POLISHED_BLACKSTONE("item/polished_blackstone", () -> Items.POLISHED_BLACKSTONE),
	POLISHED_BLACKSTONE_BRICK_SLAB("item/polished_blackstone_brick_slab", () -> Items.POLISHED_BLACKSTONE_BRICK_SLAB),
	POLISHED_BLACKSTONE_BRICK_STAIRS("item/polished_blackstone_brick_stairs",
			() -> Items.POLISHED_BLACKSTONE_BRICK_STAIRS),
	POLISHED_BLACKSTONE_BRICK_WALL("item/polished_blackstone_brick_wall", () -> Items.POLISHED_BLACKSTONE_BRICK_WALL),
	POLISHED_BLACKSTONE_BRICKS("item/polished_blackstone_bricks", () -> Items.POLISHED_BLACKSTONE_BRICKS),
	POLISHED_BLACKSTONE_BUTTON("item/polished_blackstone_button", () -> Items.POLISHED_BLACKSTONE_BUTTON),
	POLISHED_BLACKSTONE_PRESSURE_PLATE("item/polished_blackstone_pressure_plate",
			() -> Items.POLISHED_BLACKSTONE_PRESSURE_PLATE),
	POLISHED_BLACKSTONE_SLAB("item/polished_blackstone_slab", () -> Items.POLISHED_BLACKSTONE_SLAB),
	POLISHED_BLACKSTONE_STAIRS("item/polished_blackstone_stairs", () -> Items.POLISHED_BLACKSTONE_STAIRS),
	POLISHED_BLACKSTONE_WALL("item/polished_blackstone_wall", () -> Items.POLISHED_BLACKSTONE_WALL),
	POLISHED_DIORITE("item/polished_diorite", () -> Items.POLISHED_DIORITE),
	POLISHED_DIORITE_SLAB("item/polished_diorite_slab", () -> Items.POLISHED_DIORITE_SLAB),
	POLISHED_DIORITE_STAIRS("item/polished_diorite_stairs", () -> Items.POLISHED_DIORITE_STAIRS),
	POLISHED_GRANITE("item/polished_granite", () -> Items.POLISHED_GRANITE),
	POLISHED_GRANITE_SLAB("item/polished_granite_slab", () -> Items.POLISHED_GRANITE_SLAB),
	POLISHED_GRANITE_STAIRS("item/polished_granite_stairs", () -> Items.POLISHED_GRANITE_STAIRS),
	POPPED_CHORUS_FRUIT("item/popped_chorus_fruit", () -> Items.POPPED_CHORUS_FRUIT),
	POPPY("item/poppy", () -> Items.POPPY), PORKCHOP("item/porkchop", () -> Items.PORKCHOP),
	POTATO("item/potato", () -> Items.POTATO), POTION("item/potion", () -> Items.POTION),
	POWERED_RAIL("item/powered_rail", () -> Items.POWERED_RAIL), PRISMARINE("item/prismarine", () -> Items.PRISMARINE),
	PRISMARINE_BRICK_SLAB("item/prismarine_brick_slab", () -> Items.PRISMARINE_BRICK_SLAB),
	PRISMARINE_BRICK_STAIRS("item/prismarine_brick_stairs", () -> Items.PRISMARINE_BRICK_STAIRS),
	PRISMARINE_BRICKS("item/prismarine_bricks", () -> Items.PRISMARINE_BRICKS),
	PRISMARINE_CRYSTALS("item/prismarine_crystals", () -> Items.PRISMARINE_CRYSTALS),
	PRISMARINE_SHARD("item/prismarine_shard", () -> Items.PRISMARINE_SHARD),
	PRISMARINE_SLAB("item/prismarine_slab", () -> Items.PRISMARINE_SLAB),
	PRISMARINE_STAIRS("item/prismarine_stairs", () -> Items.PRISMARINE_STAIRS),
	PRISMARINE_WALL("item/prismarine_wall", () -> Items.PRISMARINE_WALL),
	PUFFERFISH("item/pufferfish", () -> Items.PUFFERFISH),
	PUFFERFISH_BUCKET("item/pufferfish_bucket", () -> Items.PUFFERFISH_BUCKET),
	PUFFERFISH_SPAWN_EGG("item/pufferfish_spawn_egg", () -> Items.PUFFERFISH_SPAWN_EGG),
	PUMPKIN("item/pumpkin", () -> Items.PUMPKIN), PUMPKIN_PIE("item/pumpkin_pie", () -> Items.PUMPKIN_PIE),
	PUMPKIN_SEEDS("item/pumpkin_seeds", () -> Items.PUMPKIN_SEEDS),
	PURPLE_BANNER("item/purple_banner", () -> Items.PURPLE_BANNER),
	PURPLE_BED("item/purple_bed", () -> Items.PURPLE_BED),
	PURPLE_CARPET("item/purple_carpet", () -> Items.PURPLE_CARPET),
	PURPLE_CONCRETE("item/purple_concrete", () -> Items.PURPLE_CONCRETE),
	PURPLE_CONCRETE_POWDER("item/purple_concrete_powder", () -> Items.PURPLE_CONCRETE_POWDER),
	PURPLE_DYE("item/purple_dye", () -> Items.PURPLE_DYE),
	PURPLE_GLAZED_TERRACOTTA("item/purple_glazed_terracotta", () -> Items.PURPLE_GLAZED_TERRACOTTA),
	PURPLE_SHULKER_BOX("item/purple_shulker_box", () -> Items.PURPLE_SHULKER_BOX),
	PURPLE_STAINED_GLASS("item/purple_stained_glass", () -> Items.PURPLE_STAINED_GLASS),
	PURPLE_STAINED_GLASS_PANE("item/purple_stained_glass_pane", () -> Items.PURPLE_STAINED_GLASS_PANE),
	PURPLE_TERRACOTTA("item/purple_terracotta", () -> Items.PURPLE_TERRACOTTA),
	PURPLE_WOOL("item/purple_wool", () -> Items.PURPLE_WOOL),
	PURPUR_BLOCK("item/purpur_block", () -> Items.PURPUR_BLOCK),
	PURPUR_PILLAR("item/purpur_pillar", () -> Items.PURPUR_PILLAR),
	PURPUR_SLAB("item/purpur_slab", () -> Items.PURPUR_SLAB),
	PURPUR_STAIRS("item/purpur_stairs", () -> Items.PURPUR_STAIRS), QUARTZ("item/quartz", () -> Items.QUARTZ),
	QUARTZ_BLOCK("item/quartz_block", () -> Items.QUARTZ_BLOCK),
	QUARTZ_BRICKS("item/quartz_bricks", () -> Items.QUARTZ_BRICKS),
	QUARTZ_PILLAR("item/quartz_pillar", () -> Items.QUARTZ_PILLAR),
	QUARTZ_SLAB("item/quartz_slab", () -> Items.QUARTZ_SLAB),
	QUARTZ_STAIRS("item/quartz_stairs", () -> Items.QUARTZ_STAIRS), RABBIT("item/rabbit", () -> Items.RABBIT),
	RABBIT_FOOT("item/rabbit_foot", () -> Items.RABBIT_FOOT), RABBIT_HIDE("item/rabbit_hide", () -> Items.RABBIT_HIDE),
	RABBIT_SPAWN_EGG("item/rabbit_spawn_egg", () -> Items.RABBIT_SPAWN_EGG),
	RABBIT_STEW("item/rabbit_stew", () -> Items.RABBIT_STEW), RAIL("item/rail", () -> Items.RAIL),
	RAVAGER_SPAWN_EGG("item/ravager_spawn_egg", () -> Items.RAVAGER_SPAWN_EGG),
	RED_BANNER("item/red_banner", () -> Items.RED_BANNER), RED_BED("item/red_bed", () -> Items.RED_BED),
	RED_CARPET("item/red_carpet", () -> Items.RED_CARPET), RED_CONCRETE("item/red_concrete", () -> Items.RED_CONCRETE),
	RED_CONCRETE_POWDER("item/red_concrete_powder", () -> Items.RED_CONCRETE_POWDER),
	RED_DYE("item/red_dye", () -> Items.RED_DYE),
	RED_GLAZED_TERRACOTTA("item/red_glazed_terracotta", () -> Items.RED_GLAZED_TERRACOTTA),
	RED_MUSHROOM("item/red_mushroom", () -> Items.RED_MUSHROOM),
	RED_MUSHROOM_BLOCK("item/red_mushroom_block", () -> Items.RED_MUSHROOM_BLOCK),
	RED_NETHER_BRICK_SLAB("item/red_nether_brick_slab", () -> Items.RED_NETHER_BRICK_SLAB),
	RED_NETHER_BRICK_STAIRS("item/red_nether_brick_stairs", () -> Items.RED_NETHER_BRICK_STAIRS),
	RED_NETHER_BRICK_WALL("item/red_nether_brick_wall", () -> Items.RED_NETHER_BRICK_WALL),
	RED_NETHER_BRICKS("item/red_nether_bricks", () -> Items.RED_NETHER_BRICKS),
	RED_SAND("item/red_sand", () -> Items.RED_SAND), RED_SANDSTONE("item/red_sandstone", () -> Items.RED_SANDSTONE),
	RED_SANDSTONE_SLAB("item/red_sandstone_slab", () -> Items.RED_SANDSTONE_SLAB),
	RED_SANDSTONE_STAIRS("item/red_sandstone_stairs", () -> Items.RED_SANDSTONE_STAIRS),
	RED_SANDSTONE_WALL("item/red_sandstone_wall", () -> Items.RED_SANDSTONE_WALL),
	RED_SHULKER_BOX("item/red_shulker_box", () -> Items.RED_SHULKER_BOX),
	RED_STAINED_GLASS("item/red_stained_glass", () -> Items.RED_STAINED_GLASS),
	RED_STAINED_GLASS_PANE("item/red_stained_glass_pane", () -> Items.RED_STAINED_GLASS_PANE),
	RED_TERRACOTTA("item/red_terracotta", () -> Items.RED_TERRACOTTA),
	RED_TULIP("item/red_tulip", () -> Items.RED_TULIP), RED_WOOL("item/red_wool", () -> Items.RED_WOOL),
	REDSTONE("item/redstone", () -> Items.REDSTONE), REDSTONE_BLOCK("item/redstone_block", () -> Items.REDSTONE_BLOCK),
	REDSTONE_LAMP("item/redstone_lamp", () -> Items.REDSTONE_LAMP),
	REDSTONE_ORE("item/redstone_ore", () -> Items.REDSTONE_ORE),
	REDSTONE_TORCH("item/redstone_torch", () -> Items.REDSTONE_TORCH), REPEATER("item/repeater", () -> Items.REPEATER),
	REPEATING_COMMAND_BLOCK("item/repeating_command_block", () -> Items.REPEATING_COMMAND_BLOCK),
	RESPAWN_ANCHOR("item/respawn_anchor", () -> Items.RESPAWN_ANCHOR),
	ROSE_BUSH("item/rose_bush", () -> Items.ROSE_BUSH), ROTTEN_FLESH("item/rotten_flesh", () -> Items.ROTTEN_FLESH),
	SADDLE("item/saddle", () -> Items.SADDLE), SALMON("item/salmon", () -> Items.SALMON),
	SALMON_BUCKET("item/salmon_bucket", () -> Items.SALMON_BUCKET),
	SALMON_SPAWN_EGG("item/salmon_spawn_egg", () -> Items.SALMON_SPAWN_EGG), SAND("item/sand", () -> Items.SAND),
	SANDSTONE("item/sandstone", () -> Items.SANDSTONE),
	SANDSTONE_SLAB("item/sandstone_slab", () -> Items.SANDSTONE_SLAB),
	SANDSTONE_STAIRS("item/sandstone_stairs", () -> Items.SANDSTONE_STAIRS),
	SANDSTONE_WALL("item/sandstone_wall", () -> Items.SANDSTONE_WALL),
	SCAFFOLDING("item/scaffolding", () -> Items.SCAFFOLDING), SCUTE("item/scute", () -> Items.SCUTE),
	SEA_LANTERN("item/sea_lantern", () -> Items.SEA_LANTERN), SEA_PICKLE("item/sea_pickle", () -> Items.SEA_PICKLE),
	SEAGRASS("item/seagrass", () -> Items.SEAGRASS), SHEARS("item/shears", () -> Items.SHEARS),
	SHEEP_SPAWN_EGG("item/sheep_spawn_egg", () -> Items.SHEEP_SPAWN_EGG), SHIELD("item/shield", () -> Items.SHIELD),
	SHROOMLIGHT("item/shroomlight", () -> Items.SHROOMLIGHT), SHULKER_BOX("item/shulker_box", () -> Items.SHULKER_BOX),
	SHULKER_SHELL("item/shulker_shell", () -> Items.SHULKER_SHELL),
	SHULKER_SPAWN_EGG("item/shulker_spawn_egg", () -> Items.SHULKER_SPAWN_EGG),
	SILVERFISH_SPAWN_EGG("item/silverfish_spawn_egg", () -> Items.SILVERFISH_SPAWN_EGG),
	SKELETON_HORSE_SPAWN_EGG("item/skeleton_horse_spawn_egg", () -> Items.SKELETON_HORSE_SPAWN_EGG),
	SKELETON_SKULL("item/skeleton_skull", () -> Items.SKELETON_SKULL),
	SKELETON_SPAWN_EGG("item/skeleton_spawn_egg", () -> Items.SKELETON_SPAWN_EGG),
	SKULL_BANNER_PATTERN("item/skull_banner_pattern", () -> Items.SKULL_BANNER_PATTERN),
	SLIME_BALL("item/slime_ball", () -> Items.SLIME_BALL), SLIME_BLOCK("item/slime_block", () -> Items.SLIME_BLOCK),
	SLIME_SPAWN_EGG("item/slime_spawn_egg", () -> Items.SLIME_SPAWN_EGG),
	SMITHING_TABLE("item/smithing_table", () -> Items.SMITHING_TABLE), SMOKER("item/smoker", () -> Items.SMOKER),
	SMOOTH_QUARTZ("item/smooth_quartz", () -> Items.SMOOTH_QUARTZ),
	SMOOTH_QUARTZ_SLAB("item/smooth_quartz_slab", () -> Items.SMOOTH_QUARTZ_SLAB),
	SMOOTH_QUARTZ_STAIRS("item/smooth_quartz_stairs", () -> Items.SMOOTH_QUARTZ_STAIRS),
	SMOOTH_RED_SANDSTONE("item/smooth_red_sandstone", () -> Items.SMOOTH_RED_SANDSTONE),
	SMOOTH_RED_SANDSTONE_SLAB("item/smooth_red_sandstone_slab", () -> Items.SMOOTH_RED_SANDSTONE_SLAB),
	SMOOTH_RED_SANDSTONE_STAIRS("item/smooth_red_sandstone_stairs", () -> Items.SMOOTH_RED_SANDSTONE_STAIRS),
	SMOOTH_SANDSTONE("item/smooth_sandstone", () -> Items.SMOOTH_SANDSTONE),
	SMOOTH_SANDSTONE_SLAB("item/smooth_sandstone_slab", () -> Items.SMOOTH_SANDSTONE_SLAB),
	SMOOTH_SANDSTONE_STAIRS("item/smooth_sandstone_stairs", () -> Items.SMOOTH_SANDSTONE_STAIRS),
	SMOOTH_STONE("item/smooth_stone", () -> Items.SMOOTH_STONE),
	SMOOTH_STONE_SLAB("item/smooth_stone_slab", () -> Items.SMOOTH_STONE_SLAB), SNOW("item/snow", () -> Items.SNOW),
	SNOW_BLOCK("item/snow_block", () -> Items.SNOW_BLOCK), SNOWBALL("item/snowball", () -> Items.SNOWBALL),
	SOUL_CAMPFIRE("item/soul_campfire", () -> Items.SOUL_CAMPFIRE),
	SOUL_LANTERN("item/soul_lantern", () -> Items.SOUL_LANTERN), SOUL_SAND("item/soul_sand", () -> Items.SOUL_SAND),
	SOUL_SOIL("item/soul_soil", () -> Items.SOUL_SOIL), SOUL_TORCH("item/soul_torch", () -> Items.SOUL_TORCH),
	SPAWNER("item/spawner", () -> Items.SPAWNER), SPECTRAL_ARROW("item/spectral_arrow", () -> Items.SPECTRAL_ARROW),
	SPIDER_EYE("item/spider_eye", () -> Items.SPIDER_EYE),
	SPIDER_SPAWN_EGG("item/spider_spawn_egg", () -> Items.SPIDER_SPAWN_EGG),
	SPLASH_POTION("item/splash_potion", () -> Items.SPLASH_POTION), SPONGE("item/sponge", () -> Items.SPONGE),
	SPRUCE_BOAT("item/spruce_boat", () -> Items.SPRUCE_BOAT),
	SPRUCE_BUTTON("item/spruce_button", () -> Items.SPRUCE_BUTTON),
	SPRUCE_DOOR("item/spruce_door", () -> Items.SPRUCE_DOOR),
	SPRUCE_FENCE("item/spruce_fence", () -> Items.SPRUCE_FENCE),
	SPRUCE_FENCE_GATE("item/spruce_fence_gate", () -> Items.SPRUCE_FENCE_GATE),
	SPRUCE_LEAVES("item/spruce_leaves", () -> Items.SPRUCE_LEAVES),
	SPRUCE_LOG("item/spruce_log", () -> Items.SPRUCE_LOG),
	SPRUCE_PLANKS("item/spruce_planks", () -> Items.SPRUCE_PLANKS),
	SPRUCE_PRESSURE_PLATE("item/spruce_pressure_plate", () -> Items.SPRUCE_PRESSURE_PLATE),
	SPRUCE_SAPLING("item/spruce_sapling", () -> Items.SPRUCE_SAPLING),
	SPRUCE_SIGN("item/spruce_sign", () -> Items.SPRUCE_SIGN), SPRUCE_SLAB("item/spruce_slab", () -> Items.SPRUCE_SLAB),
	SPRUCE_STAIRS("item/spruce_stairs", () -> Items.SPRUCE_STAIRS),
	SPRUCE_TRAPDOOR("item/spruce_trapdoor", () -> Items.SPRUCE_TRAPDOOR),
	SPRUCE_WOOD("item/spruce_wood", () -> Items.SPRUCE_WOOD),
	SQUID_SPAWN_EGG("item/squid_spawn_egg", () -> Items.SQUID_SPAWN_EGG), STICK("item/stick", () -> Items.STICK),
	STICKY_PISTON("item/sticky_piston", () -> Items.STICKY_PISTON), STONE("item/stone", () -> Items.STONE),
	STONE_AXE("item/stone_axe", () -> Items.STONE_AXE),
	STONE_BRICK_SLAB("item/stone_brick_slab", () -> Items.STONE_BRICK_SLAB),
	STONE_BRICK_STAIRS("item/stone_brick_stairs", () -> Items.STONE_BRICK_STAIRS),
	STONE_BRICK_WALL("item/stone_brick_wall", () -> Items.STONE_BRICK_WALL),
	STONE_BRICKS("item/stone_bricks", () -> Items.STONE_BRICKS),
	STONE_BUTTON("item/stone_button", () -> Items.STONE_BUTTON), STONE_HOE("item/stone_hoe", () -> Items.STONE_HOE),
	STONE_PICKAXE("item/stone_pickaxe", () -> Items.STONE_PICKAXE),
	STONE_PRESSURE_PLATE("item/stone_pressure_plate", () -> Items.STONE_PRESSURE_PLATE),
	STONE_SHOVEL("item/stone_shovel", () -> Items.STONE_SHOVEL), STONE_SLAB("item/stone_slab", () -> Items.STONE_SLAB),
	STONE_STAIRS("item/stone_stairs", () -> Items.STONE_STAIRS),
	STONE_SWORD("item/stone_sword", () -> Items.STONE_SWORD), STONECUTTER("item/stonecutter", () -> Items.STONECUTTER),
	STRAY_SPAWN_EGG("item/stray_spawn_egg", () -> Items.STRAY_SPAWN_EGG),
	STRIDER_SPAWN_EGG("item/strider_spawn_egg", () -> Items.STRIDER_SPAWN_EGG),
	STRING("item/string", () -> Items.STRING),
	STRIPPED_ACACIA_LOG("item/stripped_acacia_log", () -> Items.STRIPPED_ACACIA_LOG),
	STRIPPED_ACACIA_WOOD("item/stripped_acacia_wood", () -> Items.STRIPPED_ACACIA_WOOD),
	STRIPPED_BIRCH_LOG("item/stripped_birch_log", () -> Items.STRIPPED_BIRCH_LOG),
	STRIPPED_BIRCH_WOOD("item/stripped_birch_wood", () -> Items.STRIPPED_BIRCH_WOOD),
	STRIPPED_CRIMSON_HYPHAE("item/stripped_crimson_hyphae", () -> Items.STRIPPED_CRIMSON_HYPHAE),
	STRIPPED_CRIMSON_STEM("item/stripped_crimson_stem", () -> Items.STRIPPED_CRIMSON_STEM),
	STRIPPED_DARK_OAK_LOG("item/stripped_dark_oak_log", () -> Items.STRIPPED_DARK_OAK_LOG),
	STRIPPED_DARK_OAK_WOOD("item/stripped_dark_oak_wood", () -> Items.STRIPPED_DARK_OAK_WOOD),
	STRIPPED_JUNGLE_LOG("item/stripped_jungle_log", () -> Items.STRIPPED_JUNGLE_LOG),
	STRIPPED_JUNGLE_WOOD("item/stripped_jungle_wood", () -> Items.STRIPPED_JUNGLE_WOOD),
	STRIPPED_OAK_LOG("item/stripped_oak_log", () -> Items.STRIPPED_OAK_LOG),
	STRIPPED_OAK_WOOD("item/stripped_oak_wood", () -> Items.STRIPPED_OAK_WOOD),
	STRIPPED_SPRUCE_LOG("item/stripped_spruce_log", () -> Items.STRIPPED_SPRUCE_LOG),
	STRIPPED_SPRUCE_WOOD("item/stripped_spruce_wood", () -> Items.STRIPPED_SPRUCE_WOOD),
	STRIPPED_WARPED_HYPHAE("item/stripped_warped_hyphae", () -> Items.STRIPPED_WARPED_HYPHAE),
	STRIPPED_WARPED_STEM("item/stripped_warped_stem", () -> Items.STRIPPED_WARPED_STEM),
	STRUCTURE_BLOCK("item/structure_block", () -> Items.STRUCTURE_BLOCK),
	STRUCTURE_VOID("item/structure_void", () -> Items.STRUCTURE_VOID), SUGAR("item/sugar", () -> Items.SUGAR),
	SUGAR_CANE("item/sugar_cane", () -> Items.SUGAR_CANE), SUNFLOWER("item/sunflower", () -> Items.SUNFLOWER),
	SUSPICIOUS_STEW("item/suspicious_stew", () -> Items.SUSPICIOUS_STEW),
	SWEET_BERRIES("item/sweet_berries", () -> Items.SWEET_BERRIES),
	TALL_GRASS("item/tall_grass", () -> Items.TALL_GRASS), TARGET("item/target", () -> Items.TARGET),
	TERRACOTTA("item/terracotta", () -> Items.TERRACOTTA), TIPPED_ARROW("item/tipped_arrow", () -> Items.TIPPED_ARROW),
	TNT("item/tnt", () -> Items.TNT), TNT_MINECART("item/tnt_minecart", () -> Items.TNT_MINECART),
	TORCH("item/torch", () -> Items.TORCH), TOTEM_OF_UNDYING("item/totem_of_undying", () -> Items.TOTEM_OF_UNDYING),
	TRADER_LLAMA_SPAWN_EGG("item/trader_llama_spawn_egg", () -> Items.TRADER_LLAMA_SPAWN_EGG),
	TRAPPED_CHEST("item/trapped_chest", () -> Items.TRAPPED_CHEST), TRIDENT("item/trident", () -> Items.TRIDENT),
	TRIPWIRE_HOOK("item/tripwire_hook", () -> Items.TRIPWIRE_HOOK),
	TROPICAL_FISH("item/tropical_fish", () -> Items.TROPICAL_FISH),
	TROPICAL_FISH_BUCKET("item/tropical_fish_bucket", () -> Items.TROPICAL_FISH_BUCKET),
	TROPICAL_FISH_SPAWN_EGG("item/tropical_fish_spawn_egg", () -> Items.TROPICAL_FISH_SPAWN_EGG),
	TUBE_CORAL("item/tube_coral", () -> Items.TUBE_CORAL),
	TUBE_CORAL_BLOCK("item/tube_coral_block", () -> Items.TUBE_CORAL_BLOCK),
	TUBE_CORAL_FAN("item/tube_coral_fan", () -> Items.TUBE_CORAL_FAN),
	TURTLE_EGG("item/turtle_egg", () -> Items.TURTLE_EGG),
	TURTLE_HELMET("item/turtle_helmet", () -> Items.TURTLE_HELMET),
	TURTLE_SPAWN_EGG("item/turtle_spawn_egg", () -> Items.TURTLE_SPAWN_EGG),
	TWISTING_VINES("item/twisting_vines", () -> Items.TWISTING_VINES),
	VEX_SPAWN_EGG("item/vex_spawn_egg", () -> Items.VEX_SPAWN_EGG),
	VILLAGER_SPAWN_EGG("item/villager_spawn_egg", () -> Items.VILLAGER_SPAWN_EGG),
	VINDICATOR_SPAWN_EGG("item/vindicator_spawn_egg", () -> Items.VINDICATOR_SPAWN_EGG),
	VINE("item/vine", () -> Items.VINE),
	WANDERING_TRADER_SPAWN_EGG("item/wandering_trader_spawn_egg", () -> Items.WANDERING_TRADER_SPAWN_EGG),
	WARPED_BUTTON("item/warped_button", () -> Items.WARPED_BUTTON),
	WARPED_DOOR("item/warped_door", () -> Items.WARPED_DOOR),
	WARPED_FENCE("item/warped_fence", () -> Items.WARPED_FENCE),
	WARPED_FENCE_GATE("item/warped_fence_gate", () -> Items.WARPED_FENCE_GATE),
	WARPED_FUNGUS("item/warped_fungus", () -> Items.WARPED_FUNGUS),
	WARPED_FUNGUS_ON_A_STICK("item/warped_fungus_on_a_stick", () -> Items.WARPED_FUNGUS_ON_A_STICK),
	WARPED_HYPHAE("item/warped_hyphae", () -> Items.WARPED_HYPHAE),
	WARPED_NYLIUM("item/warped_nylium", () -> Items.WARPED_NYLIUM),
	WARPED_PLANKS("item/warped_planks", () -> Items.WARPED_PLANKS),
	WARPED_PRESSURE_PLATE("item/warped_pressure_plate", () -> Items.WARPED_PRESSURE_PLATE),
	WARPED_ROOTS("item/warped_roots", () -> Items.WARPED_ROOTS),
	WARPED_SIGN("item/warped_sign", () -> Items.WARPED_SIGN), WARPED_SLAB("item/warped_slab", () -> Items.WARPED_SLAB),
	WARPED_STAIRS("item/warped_stairs", () -> Items.WARPED_STAIRS),
	WARPED_STEM("item/warped_stem", () -> Items.WARPED_STEM),
	WARPED_TRAPDOOR("item/warped_trapdoor", () -> Items.WARPED_TRAPDOOR),
	WARPED_WART_BLOCK("item/warped_wart_block", () -> Items.WARPED_WART_BLOCK),
	WATER_BUCKET("item/water_bucket", () -> Items.WATER_BUCKET),
	WEEPING_VINES("item/weeping_vines", () -> Items.WEEPING_VINES),
	WET_SPONGE("item/wet_sponge", () -> Items.WET_SPONGE), WHEAT("item/wheat", () -> Items.WHEAT),
	WHEAT_SEEDS("item/wheat_seeds", () -> Items.WHEAT_SEEDS),
	WHITE_BANNER("item/white_banner", () -> Items.WHITE_BANNER), WHITE_BED("item/white_bed", () -> Items.WHITE_BED),
	WHITE_CARPET("item/white_carpet", () -> Items.WHITE_CARPET),
	WHITE_CONCRETE("item/white_concrete", () -> Items.WHITE_CONCRETE),
	WHITE_CONCRETE_POWDER("item/white_concrete_powder", () -> Items.WHITE_CONCRETE_POWDER),
	WHITE_DYE("item/white_dye", () -> Items.WHITE_DYE),
	WHITE_GLAZED_TERRACOTTA("item/white_glazed_terracotta", () -> Items.WHITE_GLAZED_TERRACOTTA),
	WHITE_SHULKER_BOX("item/white_shulker_box", () -> Items.WHITE_SHULKER_BOX),
	WHITE_STAINED_GLASS("item/white_stained_glass", () -> Items.WHITE_STAINED_GLASS),
	WHITE_STAINED_GLASS_PANE("item/white_stained_glass_pane", () -> Items.WHITE_STAINED_GLASS_PANE),
	WHITE_TERRACOTTA("item/white_terracotta", () -> Items.WHITE_TERRACOTTA),
	WHITE_TULIP("item/white_tulip", () -> Items.WHITE_TULIP), WHITE_WOOL("item/white_wool", () -> Items.WHITE_WOOL),
	WITCH_SPAWN_EGG("item/witch_spawn_egg", () -> Items.WITCH_SPAWN_EGG),
	WITHER_ROSE("item/wither_rose", () -> Items.WITHER_ROSE),
	WITHER_SKELETON_SKULL("item/wither_skeleton_skull", () -> Items.WITHER_SKELETON_SKULL),
	WITHER_SKELETON_SPAWN_EGG("item/wither_skeleton_spawn_egg", () -> Items.WITHER_SKELETON_SPAWN_EGG),
	WOLF_SPAWN_EGG("item/wolf_spawn_egg", () -> Items.WOLF_SPAWN_EGG),
	WOODEN_AXE("item/wooden_axe", () -> Items.WOODEN_AXE), WOODEN_HOE("item/wooden_hoe", () -> Items.WOODEN_HOE),
	WOODEN_PICKAXE("item/wooden_pickaxe", () -> Items.WOODEN_PICKAXE),
	WOODEN_SHOVEL("item/wooden_shovel", () -> Items.WOODEN_SHOVEL),
	WOODEN_SWORD("item/wooden_sword", () -> Items.WOODEN_SWORD),
	WRITABLE_BOOK("item/writable_book", () -> Items.WRITABLE_BOOK),
	WRITTEN_BOOK("item/written_book", () -> Items.WRITTEN_BOOK),
	YELLOW_BANNER("item/yellow_banner", () -> Items.YELLOW_BANNER),
	YELLOW_BED("item/yellow_bed", () -> Items.YELLOW_BED),
	YELLOW_CARPET("item/yellow_carpet", () -> Items.YELLOW_CARPET),
	YELLOW_CONCRETE("item/yellow_concrete", () -> Items.YELLOW_CONCRETE),
	YELLOW_CONCRETE_POWDER("item/yellow_concrete_powder", () -> Items.YELLOW_CONCRETE_POWDER),
	YELLOW_DYE("item/yellow_dye", () -> Items.YELLOW_DYE),
	YELLOW_GLAZED_TERRACOTTA("item/yellow_glazed_terracotta", () -> Items.YELLOW_GLAZED_TERRACOTTA),
	YELLOW_SHULKER_BOX("item/yellow_shulker_box", () -> Items.YELLOW_SHULKER_BOX),
	YELLOW_STAINED_GLASS("item/yellow_stained_glass", () -> Items.YELLOW_STAINED_GLASS),
	YELLOW_STAINED_GLASS_PANE("item/yellow_stained_glass_pane", () -> Items.YELLOW_STAINED_GLASS_PANE),
	YELLOW_TERRACOTTA("item/yellow_terracotta", () -> Items.YELLOW_TERRACOTTA),
	YELLOW_WOOL("item/yellow_wool", () -> Items.YELLOW_WOOL),
	ZOGLIN_SPAWN_EGG("item/zoglin_spawn_egg", () -> Items.ZOGLIN_SPAWN_EGG),
	ZOMBIE_HEAD("item/zombie_head", () -> Items.ZOMBIE_HEAD),
	ZOMBIE_HORSE_SPAWN_EGG("item/zombie_horse_spawn_egg", () -> Items.ZOMBIE_HORSE_SPAWN_EGG),
	ZOMBIE_SPAWN_EGG("item/zombie_spawn_egg", () -> Items.ZOMBIE_SPAWN_EGG),
	ZOMBIE_VILLAGER_SPAWN_EGG("item/zombie_villager_spawn_egg", () -> Items.ZOMBIE_VILLAGER_SPAWN_EGG),
	ZOMBIFIED_PIGLIN_SPAWN_EGG("item/zombified_piglin_spawn_egg", () -> Items.ZOMBIFIED_PIGLIN_SPAWN_EGG);

	/**
	 * This class contains a reference to all of the simple {@link VanillaItem}s.
	 * These are items that can be extended using the {@link ItemExtender} class.
	 * 
	 * @author Joseph Collard <jcollard@worldsofminecraft.com>
	 *
	 */
	public static class Simple {
		public static VanillaItem APPLE = VanillaItem.APPLE;
		public static VanillaItem ARMOR_STAND = VanillaItem.ARMOR_STAND;
		public static VanillaItem ARROW = VanillaItem.ARROW;
		public static VanillaItem BAKED_POTATO = VanillaItem.BAKED_POTATO;
		public static VanillaItem BEEF = VanillaItem.BEEF;
		public static VanillaItem BEETROOT = VanillaItem.BEETROOT;
		public static VanillaItem BEETROOT_SOUP = VanillaItem.BEETROOT_SOUP;
		public static VanillaItem BLAZE_POWDER = VanillaItem.BLAZE_POWDER;
		public static VanillaItem BLAZE_ROD = VanillaItem.BLAZE_ROD;
		public static VanillaItem BONE = VanillaItem.BONE;
		public static VanillaItem BONE_MEAL = VanillaItem.BONE_MEAL;
		public static VanillaItem BOOK = VanillaItem.BOOK;
		public static VanillaItem BOW = VanillaItem.BOW;
		public static VanillaItem BOWL = VanillaItem.BOWL;
		public static VanillaItem BREAD = VanillaItem.BREAD;
		public static VanillaItem BRICK = VanillaItem.BRICK;
		public static VanillaItem CHARCOAL = VanillaItem.CHARCOAL;
		public static VanillaItem CHICKEN = VanillaItem.CHICKEN;
		public static VanillaItem CHORUS_FRUIT = VanillaItem.CHORUS_FRUIT;
		public static VanillaItem CLAY_BALL = VanillaItem.CLAY_BALL;
		public static VanillaItem CLOCK = VanillaItem.CLOCK;
		public static VanillaItem COAL = VanillaItem.COAL;
		public static VanillaItem COD = VanillaItem.COD;
		public static VanillaItem COMPASS = VanillaItem.COMPASS;
		public static VanillaItem COOKED_BEEF = VanillaItem.COOKED_BEEF;
		public static VanillaItem COOKED_CHICKEN = VanillaItem.COOKED_CHICKEN;
		public static VanillaItem COOKED_COD = VanillaItem.COOKED_COD;
		public static VanillaItem COOKED_MUTTON = VanillaItem.COOKED_MUTTON;
		public static VanillaItem COOKED_PORKCHOP = VanillaItem.COOKED_PORKCHOP;
		public static VanillaItem COOKED_RABBIT = VanillaItem.COOKED_RABBIT;
		public static VanillaItem COOKED_SALMON = VanillaItem.COOKED_SALMON;
		public static VanillaItem COOKIE = VanillaItem.COOKIE;
		public static VanillaItem CROSSBOW = VanillaItem.CROSSBOW;
		public static VanillaItem DEBUG_STICK = VanillaItem.DEBUG_STICK;
		public static VanillaItem DIAMOND = VanillaItem.DIAMOND;
		public static VanillaItem DRAGON_BREATH = VanillaItem.DRAGON_BREATH;
		public static VanillaItem DRIED_KELP = VanillaItem.DRIED_KELP;
		public static VanillaItem EGG = VanillaItem.EGG;
		public static VanillaItem ELYTRA = VanillaItem.ELYTRA;
		public static VanillaItem EMERALD = VanillaItem.EMERALD;
		public static VanillaItem ENCHANTED_BOOK = VanillaItem.ENCHANTED_BOOK;
		public static VanillaItem ENCHANTED_GOLDEN_APPLE = VanillaItem.ENCHANTED_GOLDEN_APPLE;
		public static VanillaItem END_CRYSTAL = VanillaItem.END_CRYSTAL;
		public static VanillaItem ENDER_EYE = VanillaItem.ENDER_EYE;
		public static VanillaItem ENDER_PEARL = VanillaItem.ENDER_PEARL;
		public static VanillaItem EXPERIENCE_BOTTLE = VanillaItem.EXPERIENCE_BOTTLE;
		public static VanillaItem FEATHER = VanillaItem.FEATHER;
		public static VanillaItem FERMENTED_SPIDER_EYE = VanillaItem.FERMENTED_SPIDER_EYE;
		public static VanillaItem FILLED_MAP = VanillaItem.FILLED_MAP;
		public static VanillaItem FIRE_CHARGE = VanillaItem.FIRE_CHARGE;
		public static VanillaItem FIREWORK_ROCKET = VanillaItem.FIREWORK_ROCKET;
		public static VanillaItem FIREWORK_STAR = VanillaItem.FIREWORK_STAR;
		public static VanillaItem FISHING_ROD = VanillaItem.FISHING_ROD;
		public static VanillaItem FLINT = VanillaItem.FLINT;
		public static VanillaItem FLINT_AND_STEEL = VanillaItem.FLINT_AND_STEEL;
		public static VanillaItem GHAST_TEAR = VanillaItem.GHAST_TEAR;
		public static VanillaItem GLASS_BOTTLE = VanillaItem.GLASS_BOTTLE;
		public static VanillaItem GLISTERING_MELON_SLICE = VanillaItem.GLISTERING_MELON_SLICE;
		public static VanillaItem GLOWSTONE_DUST = VanillaItem.GLOWSTONE_DUST;
		public static VanillaItem GOLD_INGOT = VanillaItem.GOLD_INGOT;
		public static VanillaItem GOLD_NUGGET = VanillaItem.GOLD_NUGGET;
		public static VanillaItem GOLDEN_APPLE = VanillaItem.GOLDEN_APPLE;
		public static VanillaItem GOLDEN_CARROT = VanillaItem.GOLDEN_CARROT;
		public static VanillaItem GUNPOWDER = VanillaItem.GUNPOWDER;
		public static VanillaItem HEART_OF_THE_SEA = VanillaItem.HEART_OF_THE_SEA;
		public static VanillaItem HONEY_BOTTLE = VanillaItem.HONEY_BOTTLE;
		public static VanillaItem HONEYCOMB = VanillaItem.HONEYCOMB;
		public static VanillaItem INK_SAC = VanillaItem.INK_SAC;
		public static VanillaItem IRON_INGOT = VanillaItem.IRON_INGOT;
		public static VanillaItem IRON_NUGGET = VanillaItem.IRON_NUGGET;
		public static VanillaItem ITEM_FRAME = VanillaItem.ITEM_FRAME;
		public static VanillaItem KNOWLEDGE_BOOK = VanillaItem.KNOWLEDGE_BOOK;
		public static VanillaItem LAPIS_LAZULI = VanillaItem.LAPIS_LAZULI;
		public static VanillaItem LEAD = VanillaItem.LEAD;
		public static VanillaItem LEATHER = VanillaItem.LEATHER;
		public static VanillaItem LINGERING_POTION = VanillaItem.LINGERING_POTION;
		public static VanillaItem MAGMA_CREAM = VanillaItem.MAGMA_CREAM;
		public static VanillaItem MAP = VanillaItem.MAP;
		public static VanillaItem MELON_SLICE = VanillaItem.MELON_SLICE;
		public static VanillaItem MILK_BUCKET = VanillaItem.MILK_BUCKET;
		public static VanillaItem MUSHROOM_STEW = VanillaItem.MUSHROOM_STEW;
		public static VanillaItem MUTTON = VanillaItem.MUTTON;
		public static VanillaItem NAME_TAG = VanillaItem.NAME_TAG;
		public static VanillaItem NAUTILUS_SHELL = VanillaItem.NAUTILUS_SHELL;
		public static VanillaItem NETHER_BRICK = VanillaItem.NETHER_BRICK;
		public static VanillaItem NETHER_STAR = VanillaItem.NETHER_STAR;
		public static VanillaItem NETHERITE_INGOT = VanillaItem.NETHERITE_INGOT;
		public static VanillaItem NETHERITE_SCRAP = VanillaItem.NETHERITE_SCRAP;
		public static VanillaItem PAPER = VanillaItem.PAPER;
		public static VanillaItem PHANTOM_MEMBRANE = VanillaItem.PHANTOM_MEMBRANE;
		public static VanillaItem POISONOUS_POTATO = VanillaItem.POISONOUS_POTATO;
		public static VanillaItem POPPED_CHORUS_FRUIT = VanillaItem.POPPED_CHORUS_FRUIT;
		public static VanillaItem PORKCHOP = VanillaItem.PORKCHOP;
		public static VanillaItem POTION = VanillaItem.POTION;
		public static VanillaItem PRISMARINE_CRYSTALS = VanillaItem.PRISMARINE_CRYSTALS;
		public static VanillaItem PRISMARINE_SHARD = VanillaItem.PRISMARINE_SHARD;
		public static VanillaItem PUFFERFISH = VanillaItem.PUFFERFISH;
		public static VanillaItem PUMPKIN_PIE = VanillaItem.PUMPKIN_PIE;
		public static VanillaItem QUARTZ = VanillaItem.QUARTZ;
		public static VanillaItem RABBIT = VanillaItem.RABBIT;
		public static VanillaItem RABBIT_FOOT = VanillaItem.RABBIT_FOOT;
		public static VanillaItem RABBIT_HIDE = VanillaItem.RABBIT_HIDE;
		public static VanillaItem RABBIT_STEW = VanillaItem.RABBIT_STEW;
		public static VanillaItem ROTTEN_FLESH = VanillaItem.ROTTEN_FLESH;
		public static VanillaItem SADDLE = VanillaItem.SADDLE;
		public static VanillaItem SALMON = VanillaItem.SALMON;
		public static VanillaItem SCUTE = VanillaItem.SCUTE;
		public static VanillaItem SHEARS = VanillaItem.SHEARS;
		public static VanillaItem SHIELD = VanillaItem.SHIELD;
		public static VanillaItem SHULKER_SHELL = VanillaItem.SHULKER_SHELL;
		public static VanillaItem SLIME_BALL = VanillaItem.SLIME_BALL;
		public static VanillaItem SNOWBALL = VanillaItem.SNOWBALL;
		public static VanillaItem SPECTRAL_ARROW = VanillaItem.SPECTRAL_ARROW;
		public static VanillaItem SPIDER_EYE = VanillaItem.SPIDER_EYE;
		public static VanillaItem SPLASH_POTION = VanillaItem.SPLASH_POTION;
		public static VanillaItem STICK = VanillaItem.STICK;
		public static VanillaItem SUGAR = VanillaItem.SUGAR;
		public static VanillaItem SUSPICIOUS_STEW = VanillaItem.SUSPICIOUS_STEW;
		public static VanillaItem TIPPED_ARROW = VanillaItem.TIPPED_ARROW;
		public static VanillaItem TOTEM_OF_UNDYING = VanillaItem.TOTEM_OF_UNDYING;
		public static VanillaItem TRIDENT = VanillaItem.TRIDENT;
		public static VanillaItem TROPICAL_FISH = VanillaItem.TROPICAL_FISH;
		public static VanillaItem WHEAT = VanillaItem.WHEAT;
		public static VanillaItem WRITABLE_BOOK = VanillaItem.WRITABLE_BOOK;
		public static VanillaItem WRITTEN_BOOK = VanillaItem.WRITTEN_BOOK;
	}

	/** This {@link VanillaItem}s registry name */
	public final String REGISTRY_NAME;

	/**
	 * This {@link VanillaItem}s supplier. Using this supplier outside of a running
	 * game may result in errors.
	 */
	@Volatile
	public final Supplier<Item> SUPPLIER;

	private static final List<VanillaItem> items = new ArrayList<>(values().length);

	static {
		for (VanillaItem i : values()) {
			items.add(i);
		}
	}

	private VanillaItem(String registryName, Supplier<Item> itemSupplier) {
		this.REGISTRY_NAME = registryName;
		this.SUPPLIER = itemSupplier;
	}

	public static List<VanillaItem> valuesList() {
		return Collections.unmodifiableList(items);
	}

}
